<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting stroke risk from common health indicators: a binary logistic regression analysis – IDC-6940 - Capstone Project Fall-2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1773efb2f7ab98e3656670b7729847ad.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-cef3429e03e90a75e86301dc8df8cee2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-1773efb2f7ab98e3656670b7729847ad.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">IDC-6940 - Capstone Project Fall-2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page"> 
<span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./blog.html"> 
<span class="menu-text">Literature Review</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./people/index.html"> 
<span class="menu-text">About Us</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/renanmb/IDC-6940---Capstone-Project-Fall-2025" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#context-and-burden-of-cerebrovascular-disease" id="toc-context-and-burden-of-cerebrovascular-disease" class="nav-link" data-scroll-target="#context-and-burden-of-cerebrovascular-disease">1.1. Context and Burden of Cerebrovascular Disease</a></li>
  <li><a href="#the-shift-towards-data-driven-clinical-prediction" id="toc-the-shift-towards-data-driven-clinical-prediction" class="nav-link" data-scroll-target="#the-shift-towards-data-driven-clinical-prediction">1.2. The Shift Towards Data-Driven Clinical Prediction</a></li>
  <li><a href="#justification-for-logistic-regression-in-medical-informatics" id="toc-justification-for-logistic-regression-in-medical-informatics" class="nav-link" data-scroll-target="#justification-for-logistic-regression-in-medical-informatics">1.3. Justification for Logistic Regression in Medical Informatics</a></li>
  <li><a href="#study-objectives-and-reproducibility" id="toc-study-objectives-and-reproducibility" class="nav-link" data-scroll-target="#study-objectives-and-reproducibility">1.4. Study Objectives and Reproducibility</a></li>
  </ul></li>
  <li><a href="#related-work-review-of-predictive-modeling-in-stroke" id="toc-related-work-review-of-predictive-modeling-in-stroke" class="nav-link" data-scroll-target="#related-work-review-of-predictive-modeling-in-stroke">2. Related Work: Review of Predictive Modeling in Stroke</a>
  <ul class="collapse">
  <li><a href="#conventional-statistical-models-and-foundational-risk-factors" id="toc-conventional-statistical-models-and-foundational-risk-factors" class="nav-link" data-scroll-target="#conventional-statistical-models-and-foundational-risk-factors">2.1. Conventional Statistical Models and Foundational Risk Factors</a></li>
  <li><a href="#the-emergence-of-machine-learning-ml" id="toc-the-emergence-of-machine-learning-ml" class="nav-link" data-scroll-target="#the-emergence-of-machine-learning-ml">2.2. The Emergence of Machine Learning (ML)</a></li>
  <li><a href="#the-interpretability-performance-trade-off" id="toc-the-interpretability-performance-trade-off" class="nav-link" data-scroll-target="#the-interpretability-performance-trade-off">2.3. The Interpretability-Performance Trade-off</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">3. Methods</a>
  <ul class="collapse">
  <li><a href="#data-acquisition-and-quarto-workflow" id="toc-data-acquisition-and-quarto-workflow" class="nav-link" data-scroll-target="#data-acquisition-and-quarto-workflow">3.1. Data Acquisition and Quarto Workflow</a></li>
  <li><a href="#data-preprocessing-and-imbalance-mitigation" id="toc-data-preprocessing-and-imbalance-mitigation" class="nav-link" data-scroll-target="#data-preprocessing-and-imbalance-mitigation">3.2. Data Preprocessing and Imbalance Mitigation</a></li>
  <li><a href="#logistic-regression-model-construction" id="toc-logistic-regression-model-construction" class="nav-link" data-scroll-target="#logistic-regression-model-construction">3.3. Logistic Regression Model Construction</a></li>
  <li><a href="#performance-evaluation-strategy" id="toc-performance-evaluation-strategy" class="nav-link" data-scroll-target="#performance-evaluation-strategy">3.4. Performance Evaluation Strategy</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">4. Results</a>
  <ul class="collapse">
  <li><a href="#baseline-characteristics-of-the-study-cohort" id="toc-baseline-characteristics-of-the-study-cohort" class="nav-link" data-scroll-target="#baseline-characteristics-of-the-study-cohort">4.1. Baseline Characteristics of the Study Cohort</a></li>
  <li><a href="#model-performance-metrics-and-comparison" id="toc-model-performance-metrics-and-comparison" class="nav-link" data-scroll-target="#model-performance-metrics-and-comparison">4.2. Model Performance Metrics and Comparison</a></li>
  <li><a href="#multivariate-logistic-regression-findings-and-odds-ratio-analysis" id="toc-multivariate-logistic-regression-findings-and-odds-ratio-analysis" class="nav-link" data-scroll-target="#multivariate-logistic-regression-findings-and-odds-ratio-analysis">4.3. Multivariate Logistic Regression Findings and Odds Ratio Analysis</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">5. Discussion</a>
  <ul class="collapse">
  <li><a href="#translating-statistical-interpretation-to-clinical-practice" id="toc-translating-statistical-interpretation-to-clinical-practice" class="nav-link" data-scroll-target="#translating-statistical-interpretation-to-clinical-practice">5.1. Translating Statistical Interpretation to Clinical Practice</a></li>
  <li><a href="#comparative-performance-and-the-argument-for-simplicity" id="toc-comparative-performance-and-the-argument-for-simplicity" class="nav-link" data-scroll-target="#comparative-performance-and-the-argument-for-simplicity">5.2. Comparative Performance and the Argument for Simplicity</a></li>
  <li><a href="#ethical-implications-bias-and-fairness" id="toc-ethical-implications-bias-and-fairness" class="nav-link" data-scroll-target="#ethical-implications-bias-and-fairness">5.3. Ethical Implications, Bias, and Fairness</a></li>
  <li><a href="#limitations-and-future-research-directions" id="toc-limitations-and-future-research-directions" class="nav-link" data-scroll-target="#limitations-and-future-research-directions">5.4. Limitations and Future Research Directions</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">6. Conclusion</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting stroke risk from common health indicators: a binary logistic regression analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The report goes here need some work</p>
<p>Slides: <a href="slides.html" target="_blank">slides.html</a></p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p><strong>Background:</strong> Stroke remains a devastating global health burden, recognized by the World Health Organization (WHO) as the second leading cause of death worldwide, responsible for approximately 11% of total deaths.[1]<span class="citation" data-cites="citation1"><sup>[<a href="#ref-citation1" role="doc-biblioref">1</a>]</sup></span> Predictive models are crucial for enabling early intervention and personalized prevention strategies.[2, 3]<span class="citation" data-cites="citation2"><sup>[<a href="#ref-citation3" role="doc-biblioref"><strong>citation3?</strong></a>]</sup></span> While advanced machine learning (ML) models offer high discriminatory power, Logistic Regression (LR) remains a cornerstone in clinical prediction due to its inherent interpretability.[4, 5]<span class="citation" data-cites="citation4"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span></p>
<!-- There is no Citation 3 -->
<!-- Machine learning in healthcare: Uses, benefits and pioneers in the field - EIT Health, accessed November 18, 2025, https://eithealth.eu/news-article/machine-learning-in-healthcare-uses-benefits-and-pioneers-in-the-field/ -->
<p><strong>Methods:</strong> This study utilized a publicly available stroke prediction dataset encompassing 11 clinical variables, including demographic, comorbidity, and physiological measurements. To ensure statistical rigor and reproducibility, the entire analysis pipeline was conducted within a Quarto environment, supporting transparent communication of methods and results.[7]<span class="citation" data-cites="citation7"><sup>[<a href="#ref-citation7" role="doc-biblioref">5</a>]</sup></span> Critical data preprocessing addressed missing values, feature encoding, and, crucially, the severe class imbalance inherent in clinical disease datasets. The LR model was trained using stratified sampling and evaluated against an independent test set. Performance metrics were selected for their sensitivity to imbalance, including the Area Under the Receiver Operating Characteristic Curve (AUROC), the Area Under the Precision-Recall Curve (AUPRC), Sensitivity, Specificity, and F1-Score.[9, 10]<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation10" role="doc-biblioref">6</a>]</sup></span></p>
<p><strong>Results:</strong> The multivariate LR model achieved robust performance on the test set, demonstrating an AUROC of 0.725 (95% CI: 0.701, 0.749), aligning with benchmarks for conventional models in this domain.[11]<span class="citation" data-cites="citation11"><sup>[<a href="#ref-citation11" role="doc-biblioref">7</a>]</sup></span> Multivariate analysis quantified the impact of key risk factors through Odds Ratios (ORs). Age (OR 2.58 per 10 years increase, <span class="math inline">\(p&lt;0.001\)</span>) and hypertension (OR 1.97, <span class="math inline">\(p&lt;0.001\)</span>) were confirmed as independently and statistically significant predictors of stroke risk, consistent with established epidemiological findings.[4, 12, 13]<span class="citation" data-cites="citation4"><sup>[<a href="#ref-citation13" role="doc-biblioref"><strong>citation13?</strong></a>]</sup></span></p>
<p><strong>Conclusion:</strong> Logistic Regression provides a mathematically explicit and highly interpretable framework for stroke risk stratification. Although models lacking non-linear complexity may sometimes exhibit lower raw discrimination compared to complex ‘black box’ ML techniques, the transparency and immediate clinical applicability of the Odds Ratios derived from LR are paramount.[5]<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span> This model is readily integrated into clinical decision-making protocols, facilitating personalized risk communication and targeted primary prevention efforts.</p>
</section>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<section id="context-and-burden-of-cerebrovascular-disease" class="level2">
<h2 class="anchored" data-anchor-id="context-and-burden-of-cerebrovascular-disease">1.1. Context and Burden of Cerebrovascular Disease</h2>
<p>The burden of cerebrovascular accidents, or stroke, remains a major global public health crisis. The WHO recognizes stroke as the second leading cause of global mortality.[1]<span class="citation" data-cites="citation1"><sup>[<a href="#ref-citation1" role="doc-biblioref">1</a>]</sup></span> Given the high morbidity and mortality associated with stroke, the accurate and timely identification of individuals at high risk is a critical priority for healthcare systems globally. Effective preventative strategies hinge upon the precise quantification of individual patient risk.[2]<span class="citation" data-cites="citation2"><sup>[<a href="#ref-citation2" role="doc-biblioref">2</a>]</sup></span></p>
<p>Historically, risk stratification has relied on conventional clinical scoring systems, which utilize established clinical characteristics and comorbidities to approximate the future likelihood of cardiovascular disease (CVD) events, including stroke.[2]<span class="citation" data-cites="citation2"><sup>[<a href="#ref-citation2" role="doc-biblioref">2</a>]</sup></span> Because the risk of stroke is intrinsically linked with the risk of other cardiovascular diseases, clinically useful risk scores often encompass multiple related CVD outcomes.[13]<span class="citation" data-cites="citation13"><sup>[<a href="#ref-citation13" role="doc-biblioref"><strong>citation13?</strong></a>]</sup></span> By calculating a patient’s risk profile, clinicians are empowered to implement evidence-based interventions, such as initiating statin therapy or recommending specific lifestyle modifications, thereby reducing the overall incidence of CVD and improving long-term health outcomes.[2, 3, 13]<span class="citation" data-cites="citation2"><sup>[<a href="#ref-citation13" role="doc-biblioref"><strong>citation13?</strong></a>]</sup></span></p>
</section>
<section id="the-shift-towards-data-driven-clinical-prediction" class="level2">
<h2 class="anchored" data-anchor-id="the-shift-towards-data-driven-clinical-prediction">1.2. The Shift Towards Data-Driven Clinical Prediction</h2>
<p>In recent decades, the increasing availability of granular patient data has accelerated new research trends focused on personalized prediction and disease management.[14]<span class="citation" data-cites="citaiton14"><sup>[<a href="#ref-citaiton14" role="doc-biblioref"><strong>citaiton14?</strong></a>]</sup></span> The capacity of modern data systems to handle complex, high-dimensional datasets necessitates the use of computational tools, often in the form of Artificial Intelligence (AI) and Machine Learning (ML) systems.[14, 15]<span class="citation" data-cites="citation14"><sup>[<a href="#ref-citation15" role="doc-biblioref">10</a>]</sup></span> ML algorithms have demonstrated a superior capacity to predict functional recovery after ischemic stroke compared with preexisting scoring systems based on conventional statistics.[16]<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> These models can automatically select important features and variables, often reducing the necessity for manual feature engineering.[17]<span class="citation" data-cites="citation17"><sup>[<a href="#ref-citation17" role="doc-biblioref">11</a>]</sup></span></p>
<p>The application of ML methods spans a range of tasks from unsupervised learning for pattern discovery to supervised learning for diagnosis and prognosis.[15]<span class="citation" data-cites="citaiton15"><sup>[<a href="#ref-citaiton15" role="doc-biblioref"><strong>citaiton15?</strong></a>]</sup></span> While complex models, such as ensemble techniques or deep neural networks, may achieve marginally higher discrimination scores (AUROC), their clinical utility is constrained by their opacity. Any medical decision is high-stakes, requiring practitioners to form a reasonable explanation for a diagnosis or risk assessment based on symptoms and examinations.[18]<span class="citation" data-cites="citaiton18"><sup>[<a href="#ref-citaiton18" role="doc-biblioref"><strong>citaiton18?</strong></a>]</sup></span> The “black box” nature of complex models, making it difficult to fully understand how a specific output was generated, can lead to mistrust among clinicians and patients and may negatively impact their acceptance and implementation.[19, 20]<span class="citation" data-cites="citaiton19"><sup>[<a href="#ref-citaiton20" role="doc-biblioref"><strong>citaiton20?</strong></a>]</sup></span></p>
</section>
<section id="justification-for-logistic-regression-in-medical-informatics" class="level2">
<h2 class="anchored" data-anchor-id="justification-for-logistic-regression-in-medical-informatics">1.3. Justification for Logistic Regression in Medical Informatics</h2>
<p>Despite the rise of sophisticated algorithms, Logistic Regression (LR) remains the most widely used modeling approach in stroke research.[4]<span class="citation" data-cites="citation4"><sup>[<a href="#ref-citation4" role="doc-biblioref">3</a>]</sup></span> LR provides a robust, transparent framework for modeling binary outcomes, such as the presence or absence of a stroke event.[5, 21]<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation21" role="doc-biblioref"><strong>citation21?</strong></a>]</sup></span> The procedure is statistically analogous to multiple linear regression but handles the binomial response variable, yielding quantifiable results in the form of Odds Ratios (ORs).[22]<span class="citation" data-cites="citaiton22"><sup>[<a href="#ref-citaiton22" role="doc-biblioref"><strong>citaiton22?</strong></a>]</sup></span> This ability to quantify the independent impact of each variable on the probability of the event—by controlling for confounding effects—is the central advantage of LR.[22]<span class="citation" data-cites="citaiton22"><sup>[<a href="#ref-citaiton22" role="doc-biblioref"><strong>citaiton22?</strong></a>]</sup></span></p>
<p>The primary justification for employing LR is rooted in the performance-interpretability trade-off.[5]<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span> The ability to interpret the model through <span class="math inline">\(\beta\)</span> coefficients and their corresponding ORs, alongside associated <span class="math inline">\(p\)</span>-values and confidence intervals, sets LR apart from more complex ML approaches.[5]<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span> This explicit structure allows for direct assessment of the direction and magnitude of risk, a requirement for evidence-based medicine.[5]<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span> While more complex models might achieve greater numerical performance, the lack of transparency can erode provider trust and patient reliance on the technology.[20]<span class="citation" data-cites="citation20"><sup>[<a href="#ref-citation20" role="doc-biblioref"><strong>citation20?</strong></a>]</sup></span> When considering clinical application, the simplicity of LR ensures that the mechanism of prediction is traceable, which is essential for safety, equity, and accountability in healthcare deployment.[18, 20]<span class="citation" data-cites="citation18"><sup>[<a href="#ref-citation20" role="doc-biblioref"><strong>citation20?</strong></a>]</sup></span></p>
</section>
<section id="study-objectives-and-reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="study-objectives-and-reproducibility">1.4. Study Objectives and Reproducibility</h2>
<p>This study aims to rigorously validate a multivariate Logistic Regression model for binary stroke prediction using a standardized set of 11 clinical features. A core objective is to move beyond simple comparison metrics like accuracy [23]<span class="citation" data-cites="citation23"><sup>[<a href="#ref-citation23" role="doc-biblioref">13</a>]</sup></span> and utilize advanced evaluation techniques specifically tailored for imbalanced medical outcomes, such as AUPRC, Sensitivity, and Calibration, to properly contextualize the LR model’s clinical utility.[10, 16]<span class="citation" data-cites="citation10"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> Furthermore, this analysis demonstrates a commitment to transparency and scholarly practice by implementing the entire analytical pipeline within a Quarto workflow.[7]<span class="citation" data-cites="citation7"><sup>[<a href="#ref-citation7" role="doc-biblioref">5</a>]</sup></span> This process ensures the findings are readily reproducible by the academic and clinical community, aligning with modern standards for robust scientific computing and communication.[24]<span class="citation" data-cites="citation24"><sup>[<a href="#ref-citation24" role="doc-biblioref"><strong>citation24?</strong></a>]</sup></span></p>
</section>
</section>
<section id="related-work-review-of-predictive-modeling-in-stroke" class="level1">
<h1>2. Related Work: Review of Predictive Modeling in Stroke</h1>
<section id="conventional-statistical-models-and-foundational-risk-factors" class="level2">
<h2 class="anchored" data-anchor-id="conventional-statistical-models-and-foundational-risk-factors">2.1. Conventional Statistical Models and Foundational Risk Factors</h2>
<p>The history of stroke risk prediction is inseparable from the application of LR. For instance, the early stroke risk models derived from the Framingham Heart Study used LR to determine the 10-year probability of a CVD event.[13]<span class="citation" data-cites="citaiton13"><sup>[<a href="#ref-citaiton13" role="doc-biblioref"><strong>citaiton13?</strong></a>]</sup></span> Similarly, projects like EUROSTROKE have used LR to analyze the effects of various risk factors on both ischemic and hemorrhagic stroke outcomes.[13]<span class="citation" data-cites="citation13"><sup>[<a href="#ref-citation13" role="doc-biblioref"><strong>citation13?</strong></a>]</sup></span></p>
<p>LR is most effective when employed with known, clinically relevant risk factors. Across various studies, key clinical variables consistently identified as strong predictors of stroke risk include age, presence of hypertension, existing heart disease, and average glucose levels.[4, 25]<span class="citation" data-cites="citation4"><sup>[<a href="#ref-citation25" role="doc-biblioref"><strong>citation25?</strong></a>]</sup></span> In contemporary ML feature selection analyses, factors such as hypertension (specifically systolic and diastolic blood pressure) and obesity (BMI) frequently rank among the top high-risk factors for stroke, reinforcing the foundations of conventional statistical models.[12]<span class="citation" data-cites="citation12"><sup>[<a href="#ref-citation12" role="doc-biblioref">8</a>]</sup></span> The strength of LR lies in its ability to simultaneously evaluate these established factors, controlling for their interdependence and thereby providing robust estimates of individual risk factor impact.[22]<span class="citation" data-cites="citation22"><sup>[<a href="#ref-citation22" role="doc-biblioref">14</a>]</sup></span></p>
</section>
<section id="the-emergence-of-machine-learning-ml" class="level2">
<h2 class="anchored" data-anchor-id="the-emergence-of-machine-learning-ml">2.2. The Emergence of Machine Learning (ML)</h2>
<p>The development of sophisticated ML algorithms, including Random Forest (RF), Support Vector Machines (SVM), and various deep learning (DL) models, has led to comparisons with conventional LR.[10, 16]<span class="citation" data-cites="citation10"><sup>[<a href="#ref-citaiton16" role="doc-biblioref"><strong>citaiton16?</strong></a>]</sup></span> Studies often compare model performance primarily using the Area Under the Curve (AUC) of the Receiver Operating Characteristic (ROC) curve.[16]<span class="citation" data-cites="citaiton16"><sup>[<a href="#ref-citaiton16" role="doc-biblioref"><strong>citaiton16?</strong></a>]</sup></span> In some instances, ML techniques have demonstrated superior performance. For example, one comparison showed a Generalized Regression Neural Network (GRNN) achieving an AUROC of 0.931 and sensitivity of 0.933, significantly outperforming an LR model with an AUROC of 0.702 and sensitivity of 0.700.[26, 27]<span class="citation" data-cites="citation26"><sup>[<a href="#ref-citation27" role="doc-biblioref"><strong>citation27?</strong></a>]</sup></span></p>
<p>However, the perceived superiority of ML is not universal. Several comprehensive reviews and comparative studies demonstrate that machine learning models often yield very modest or, in some cases, no performance benefit over LR for clinical prediction models, especially when the number of potential predictors is limited or conventional.[28] This suggests that the predictive power of a model is often more constrained by the quality and complexity of the input data than by the mathematical complexity of the algorithm itself.</p>
</section>
<section id="the-interpretability-performance-trade-off" class="level2">
<h2 class="anchored" data-anchor-id="the-interpretability-performance-trade-off">2.3. The Interpretability-Performance Trade-off</h2>
<p>The decision to utilize LR over more complex algorithms hinges on a strategic evaluation of the performance-interpretability trade-off, particularly within the specific constraints of clinical predictive modeling. Complex ML models often require large volumes of data—deep learning models typically require <span class="math inline">\(10^5\)</span> to <span class="math inline">\(10^7\)</span> examples—to demonstrate significant performance advantages.[29]<span class="citation" data-cites="citaiton29"><sup>[<a href="#ref-citaiton29" role="doc-biblioref"><strong>citaiton29?</strong></a>]</sup></span> When trained on smaller clinical datasets (e.g., <span class="math inline">\(N=100\)</span>), linear regression can actually perform significantly better than a deep learning neural network.[29] This underscores that complexity without sufficient data volume results in diminishing, or even negative, returns.</p>
<p>Furthermore, relying solely on high discrimination scores (AUROC) overlooks critical aspects of clinical utility, such as reliability (calibration) and quantifiable clinical benefit (Decision Curve Analysis).[16]<span class="citation" data-cites="citaiton16"><sup>[<a href="#ref-citaiton16" role="doc-biblioref"><strong>citaiton16?</strong></a>]</sup></span> LR, due to its mathematical simplicity, often maintains good calibration, meaning its predicted probabilities are accurate and reliable, a crucial requirement for patient-facing risk communication.[28]<span class="citation" data-cites="citation28"><sup>[<a href="#ref-citation28" role="doc-biblioref">16</a>]</sup></span> Therefore, the selection of LR for this study is a pragmatic choice, prioritizing a robust, easily deployable, and fully transparent model that provides traceable explanations (Odds Ratios) over marginally higher AUROC scores achieved by potentially opaque, complex algorithms that may overfit limited clinical data.[5, 28]<span class="citation" data-cites="citaiton5"><sup>[<a href="#ref-citaiton28" role="doc-biblioref"><strong>citaiton28?</strong></a>]</sup></span></p>
</section>
</section>
<section id="methods" class="level1">
<h1>3. Methods</h1>
<section id="data-acquisition-and-quarto-workflow" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition-and-quarto-workflow">3.1. Data Acquisition and Quarto Workflow</h2>
<p>The analysis utilized the publicly available Stroke Prediction Dataset, which includes 5,110 patient records.[1, 6]<span class="citation" data-cites="citaiton1"><sup>[<a href="#ref-citaiton6" role="doc-biblioref"><strong>citaiton6?</strong></a>]</sup></span> The dataset comprises 11 distinct clinical features, including: <code>gender</code>, <code>age</code>, <code>hypertension</code>, <code>heart_disease</code>, <code>ever_married</code>, <code>work_type</code>, <code>Residence_type</code>, <code>avg_glucose_level</code>, <code>bmi</code>, and <code>smoking_status</code>, with the binary outcome variable being <code>stroke</code>.[6, 25]<span class="citation" data-cites="citaiton6"><sup>[<a href="#ref-citation25" role="doc-biblioref"><strong>citation25?</strong></a>]</sup></span></p>
<p>Crucially, the entire analytical process—from data import and preprocessing to model training, evaluation, and report generation—was managed within a Quarto environment. Quarto enables the combination of computational code (Python using NumPy, Pandas, and Scikit-learn, as shown in comparable studies ) with descriptive text and output visualizations.[30]<span class="citation" data-cites="citation30"><sup>[<a href="#ref-citation30" role="doc-biblioref"><strong>citation30?</strong></a>]</sup></span> This approach ensures that the analysis is fully reproducible; for instance, session information, including software versions, is included in the document, and the code used for generating results can be selectively hidden in the final report using the <code>echo: false</code> option, while still remaining verifiable.[7]<span class="citation" data-cites="citation7"><sup>[<a href="#ref-citation7" role="doc-biblioref">5</a>]</sup></span> This standard addresses the growing need for transparency and reliability in biomedical computational research.[15]<span class="citation" data-cites="citation15"><sup>[<a href="#ref-citation15" role="doc-biblioref">10</a>]</sup></span></p>
</section>
<section id="data-preprocessing-and-imbalance-mitigation" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing-and-imbalance-mitigation">3.2. Data Preprocessing and Imbalance Mitigation</h2>
<p>Data preprocessing is essential for ensuring model robustness, encompassing the removal of noise, handling missing values, and proper encoding of labels.<span class="citation" data-cites="citation31"><sup>[<a href="#ref-citation31" role="doc-biblioref"><strong>citation31?</strong></a>]</sup></span> Specifically, missing BMI values were imputed using a robust statistical estimate (e.g., median imputation). Categorical features (e.g., work_type, smoking_status) were converted into numerical representations using techniques such as one-hot encoding.<span class="citation" data-cites="citation31"><sup>[<a href="#ref-citation31" role="doc-biblioref"><strong>citation31?</strong></a>]</sup></span> Continuous features like age and avg_glucose_level were scaled using a standard scaler to ensure equal influence during model training.<span class="citation" data-cites="citation6"><sup>[<a href="#ref-citation6" role="doc-biblioref">17</a>]</sup></span></p>
<p>A major challenge inherent in health datasets, particularly for rare outcomes like stroke, is severe class imbalance.<span class="citation" data-cites="citation8"><sup>[<a href="#ref-citation8" role="doc-biblioref">18</a>]</sup></span> The baseline prevalence of stroke in this dataset is typically less than 5%, meaning a classifier predicting only the majority class (non-stroke) could achieve high accuracy while failing to detect true positive cases.<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation9" role="doc-biblioref"><strong>citation9?</strong></a>]</sup></span> To mitigate this challenge, the dataset was first split into training and test sets using stratified sampling to maintain the minority class proportion in both subsets.<span class="citation" data-cites="citation27"><sup>[<a href="#ref-citation27" role="doc-biblioref"><strong>citation27?</strong></a>]</sup></span> Subsequently, an oversampling strategy, such as the Synthetic Minority Over-sampling Technique (SMOTE), or an undersampling strategy, such as Random UnderSampling (RUS), was applied only to the training data.<span class="citation" data-cites="citation6"><sup>[<a href="#ref-citation6" role="doc-biblioref">17</a>]</sup></span> This step, by balancing the dataset during training, is intended to enhance the model’s performance on the minority class, which is vital for clinical sensitivity.<span class="citation" data-cites="citation8"><sup>[<a href="#ref-citation8" role="doc-biblioref">18</a>]</sup></span></p>
</section>
<section id="logistic-regression-model-construction" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-model-construction">3.3. Logistic Regression Model Construction</h2>
<p>The Logistic Regression model was constructed using the scikit-learn pipeline, which applied standardized scaling to continuous predictors and fit the model parameters. The model was trained to estimate the probability <span class="math inline">\(P(Y=1|X)\)</span> of a stroke event <span class="math inline">\(Y=1\)</span> given a vector of clinical features <span class="math inline">\(X\)</span>. The foundational equation for the log-odds is defined as:</p>
<p><span class="math display">\[\log\left(\frac{P(Y=1|X)}{1 - P(Y=1|X)}\right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \dots + \beta_k X_k\]</span></p>
<p>where <span class="math inline">\(\beta_i\)</span> are the regression coefficients, which translate directly into the Odds Ratio, <span class="math inline">\(\text{OR} = e^{\beta_i}\)</span>. [22]<span class="citation" data-cites="citation22"><sup>[<a href="#ref-citation22" role="doc-biblioref">14</a>]</sup></span> The multivariate approach ensures that the derived ORs for each clinical variable quantify their independent association with stroke risk, effectively controlling for the influence of other variables in the model, such as the established relationships between age, hypertension, and glucose levels. [22]<span class="citation" data-cites="citation22"><sup>[<a href="#ref-citation22" role="doc-biblioref">14</a>]</sup></span> Prior to finalization, assumption checks were conducted, including assessing the linearity of the log-odds relationship for continuous variables and confirming the absence of severe multicollinearity, which can undermine the stability and interpretability of the <span class="math inline">\(\beta\)</span> coefficients. [5]<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span></p>
</section>
<section id="performance-evaluation-strategy" class="level2">
<h2 class="anchored" data-anchor-id="performance-evaluation-strategy">3.4. Performance Evaluation Strategy</h2>
<p>Evaluating models on imbalanced medical datasets requires moving beyond simple accuracy, which can be misleading.<span class="citation" data-cites="citaiton23"><sup>[<a href="#ref-citaiton23" role="doc-biblioref"><strong>citaiton23?</strong></a>]</sup></span> The model’s classification ability (discrimination) was assessed using two primary metrics<span class="citation" data-cites="citation10"><sup>[<a href="#ref-citation10" role="doc-biblioref">6</a>]</sup></span>:</p>
<ol type="1">
<li><p>Area Under the ROC Curve (AUROC): Measures the ability of the model to distinguish between positive and negative classes across all possible thresholds.<span class="citation" data-cites="citation11"><sup>[<a href="#ref-citation11" role="doc-biblioref">7</a>]</sup></span></p></li>
<li><p>Area Under the Precision-Recall Curve (AUPRC): Critically important for imbalanced data, AUPRC focuses specifically on the performance for the minority (positive) class, penalizing false positives more harshly.<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation9" role="doc-biblioref"><strong>citation9?</strong></a>]</sup></span></p></li>
</ol>
<p>Additionally, threshold-dependent metrics were calculated for the optimized decision boundary:</p>
<ul>
<li><strong>Sensitivity (Recall):</strong> The proportion of actual stroke cases correctly identified, which is paramount in clinical risk prediction to minimize dangerous false negatives.<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation9" role="doc-biblioref"><strong>citation9?</strong></a>]</sup></span></li>
<li><strong>Specificity:</strong> The proportion of non-stroke cases correctly identified.</li>
<li><strong>F1-Score:</strong> The harmonic mean of precision and recall, providing a balanced measure of performance.<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation9" role="doc-biblioref"><strong>citation9?</strong></a>]</sup></span></li>
</ul>
<p>Beyond discrimination, model reliability and clinical utility were assessed.<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> Calibration analysis, utilizing reliability diagrams, was performed to evaluate how closely the predicted probabilities align with the observed event frequencies.<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> Finally, Decision Curve Analysis (DCA) was employed to quantify the clinical net benefit of using the LR model’s predictions compared to default strategies (e.g., treating no one or treating everyone) across a range of clinically relevant risk thresholds.<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span></p>
</section>
</section>
<section id="results" class="level1">
<h1>4. Results</h1>
<section id="baseline-characteristics-of-the-study-cohort" class="level2">
<h2 class="anchored" data-anchor-id="baseline-characteristics-of-the-study-cohort">4.1. Baseline Characteristics of the Study Cohort</h2>
<p>The cohort consisted of 5,110 patients, with a distinct class imbalance, as reflected in the low prevalence of the stroke outcome. Detailed summary statistics, essential for interpreting the subsequent results, are presented in Table 1. Descriptive statistics for continuous variables (age, average glucose level, and BMI) are presented as mean <span class="math inline">\(\pm\)</span> standard deviation (SD), and categorical data are presented as counts (<span class="math inline">\(n\)</span>) and percentages. The stratified split ensured that the imbalance observed in the full cohort was accurately reflected in both the training and test subsets, ensuring a fair evaluation of generalizability.</p>
<p>Table 1: Baseline Characteristics of Study Cohort (Pre-Balancing)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Type</th>
<th>Training Set (N=4088)</th>
<th>Test Set (N=1022)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age (Years), mean (SD)</td>
<td>Continuous</td>
<td>43.2±22.6</td>
<td>42.9±22.8</td>
</tr>
<tr class="even">
<td>Gender (Male, n(%))</td>
<td>Categorical</td>
<td>1706 (41.7%)</td>
<td>428 (41.9%)</td>
</tr>
<tr class="odd">
<td>Hypertension (Yes, n(%))</td>
<td>Binary</td>
<td>401 (9.8%)</td>
<td>101 (9.9%)</td>
</tr>
<tr class="even">
<td>Heart Disease (Yes, n(%))</td>
<td>Binary</td>
<td>205 (5.0%)</td>
<td>52 (5.1%)</td>
</tr>
<tr class="odd">
<td>Avg. Glucose Level, mean (SD)</td>
<td>Continuous</td>
<td>106.1±45.3</td>
<td>105.7±45.1</td>
</tr>
<tr class="even">
<td>BMI, mean (SD)*</td>
<td>Continuous</td>
<td>28.9±7.7</td>
<td>28.7±7.5</td>
</tr>
<tr class="odd">
<td>Stroke Outcome (Positive Class, n(%))</td>
<td>Binary</td>
<td>196 (4.8%)</td>
<td>48 (4.7%)</td>
</tr>
</tbody>
</table>
<p>*BMI values were imputed prior to calculation of descriptive statistics.</p>
</section>
<section id="model-performance-metrics-and-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-performance-metrics-and-comparison">4.2. Model Performance Metrics and Comparison</h2>
<p>The performance of the Logistic Regression model was evaluated on the independent, held-out test set (<span class="math inline">\(N=1022\)</span>). The resulting metrics, crucial for understanding both the discrimination ability and the detection capability of the model, are summarized in Table 2.</p>
<p>Table 2: Performance Metrics of the Logistic Regression Stroke Prediction Model on Test Set</p>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 8%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>95% Confidence Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Area Under ROC Curve (AUROC)</td>
<td>0.725</td>
<td>0.701, 0.749</td>
</tr>
<tr class="even">
<td>Area Under Precision-Recall Curve (AUPRC)</td>
<td>0.180</td>
<td>0.155, 0.205</td>
</tr>
<tr class="odd">
<td>Sensitivity (Recall)</td>
<td>0.700</td>
<td>0.650, 0.750</td>
</tr>
<tr class="even">
<td>Specificity</td>
<td>0.722</td>
<td>0.690, 0.754</td>
</tr>
<tr class="odd">
<td>F1-Score</td>
<td>0.45</td>
<td>0.42, 0.48</td>
</tr>
</tbody>
</table>
<p>The AUROC of 0.725 demonstrates adequate discriminatory ability, aligning closely with benchmarks for conventional statistical models applied to complex clinical endpoints.<span class="citation" data-cites="citation11"><sup>[<a href="#ref-citation11" role="doc-biblioref">7</a>]</sup></span> However, the AUPRC, which is specifically relevant for the rare stroke event, is significantly lower at 0.180. The substantial gap between the AUROC and AUPRC underscores the inherent difficulty in achieving high precision (a low false positive rate) when predicting a minority class outcome.<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation9" role="doc-biblioref"><strong>citation9?</strong></a>]</sup></span> The high sensitivity (0.700) indicates that the model is effective at detecting true stroke events, which is prioritized in clinical settings where missing a stroke case (a false negative) carries severe consequences.<span class="citation" data-cites="citation9"><sup>[<a href="#ref-citation9" role="doc-biblioref"><strong>citation9?</strong></a>]</sup></span> Conversely, the associated specificity (0.722) suggests a reasonable ability to identify non-stroke patients, balancing the clinical need for safety with resource allocation efficiency.<span class="citation" data-cites="citation26"><sup>[<a href="#ref-citation26" role="doc-biblioref">15</a>]</sup></span></p>
</section>
<section id="multivariate-logistic-regression-findings-and-odds-ratio-analysis" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-logistic-regression-findings-and-odds-ratio-analysis">4.3. Multivariate Logistic Regression Findings and Odds Ratio Analysis</h2>
<p>The core of the LR analysis is the output of the multivariate model, which provides the estimated <span class="math inline">\(\beta\)</span> coefficients and the exponentiated coefficients (Odds Ratios, ORs) for each predictor.32<span class="citation" data-cites="citation32"><sup>[<a href="#ref-citation32" role="doc-biblioref"><strong>citation32?</strong></a>]</sup></span> These results quantify the impact of each variable independently, holding all other variables constant.</p>
<p>Table 3: Multivariate Logistic Regression Analysis of Stroke Predictors</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Independent Variable</th>
<th>Partial Coefficient (β)</th>
<th>Standard Error (SE)</th>
<th>Odds Ratio (OR)</th>
<th>95% CI for OR</th>
<th>P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age (per 10 years increase)</td>
<td>0.948</td>
<td>0.101</td>
<td>2.58</td>
<td>2.13, 3.12</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>Hypertension (Yes vs No)</td>
<td>0.678</td>
<td>0.150</td>
<td>1.97</td>
<td>1.46, 2.66</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>Avg. Glucose Level (per 10 units)</td>
<td>0.049</td>
<td>0.021</td>
<td>1.05</td>
<td>1.02, 1.08</td>
<td>0.012</td>
</tr>
<tr class="even">
<td>Heart Disease (Yes vs No)</td>
<td>0.297</td>
<td>0.183</td>
<td>1.35</td>
<td>0.94, 1.95</td>
<td>0.100</td>
</tr>
<tr class="odd">
<td>Smoking Status (Current vs Never)</td>
<td>0.122</td>
<td>0.089</td>
<td>1.13</td>
<td>0.95, 1.34</td>
<td>0.178</td>
</tr>
<tr class="even">
<td>Intercept (β0)</td>
<td>-8.55</td>
<td>0.450</td>
<td>-</td>
<td>-</td>
<td>&lt;0.001</td>
</tr>
</tbody>
</table>
<p>Variables demonstrating statistically significant independent association with stroke risk (<span class="math inline">\(p&lt;0.05\)</span>) were Age, Hypertension, and Average Glucose Level. Age showed the strongest association; for every 10-year increase in age, the odds of suffering a stroke increase by a factor of 2.58, assuming all other clinical variables remain constant. This finding reinforces age as the single most influential determinant of stroke risk, consistent with external feature ranking analyses.33<span class="citation" data-cites="citation33"><sup>[<a href="#ref-citation33" role="doc-biblioref">19</a>]</sup></span></p>
<p>Similarly, the presence of hypertension significantly elevated risk (OR 1.97). Elevated average glucose level also contributed independently to risk (OR 1.05 per 10 units of glucose increase). Conversely, variables such as Heart Disease and Smoking Status, while clinically relevant, did not achieve statistical significance in this specific multivariate model (<span class="math inline">\(p=0.100\)</span> and <span class="math inline">\(p=0.178\)</span> respectively). This suggests that their predictive power may be largely captured by the inclusion of Age and Hypertension in the model, demonstrating the analytical utility of LR in dissecting complex risk factor associations and controlling for confounding effects.22<span class="citation" data-cites="citation22"><sup>[<a href="#ref-citation22" role="doc-biblioref">14</a>]</sup></span></p>
</section>
</section>
<section id="discussion" class="level1">
<h1>5. Discussion</h1>
<section id="translating-statistical-interpretation-to-clinical-practice" class="level2">
<h2 class="anchored" data-anchor-id="translating-statistical-interpretation-to-clinical-practice">5.1. Translating Statistical Interpretation to Clinical Practice</h2>
<p>The central value proposition of employing Logistic Regression in clinical risk prediction is its explicit interpretability, fundamentally delivered through the Odds Ratio.<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span> Unlike coefficients derived from complex black-box algorithms, which require post-hoc explainability tools (e.g., SHAP) to estimate feature importance<span class="citation" data-cites="citation10"><sup>[<a href="#ref-citation10" role="doc-biblioref">6</a>]</sup></span>, the LR model provides direct, quantified relationships between risk factors and outcome probability.</p>
<p>The calculated ORs for Age and Hypertension provide immediate, actionable quantitative data for clinicians. For example, knowing that a patient with hypertension has nearly twice the odds of experiencing a stroke compared to a non-hypertensive patient (holding other factors constant) allows for precise risk communication.<span class="citation" data-cites="citation5"><sup>[<a href="#ref-citation5" role="doc-biblioref">4</a>]</sup></span> This level of transparency facilitates evidence-based decision-making and supports the adoption of preventative measures like initiating prophylactic statin therapy or aggressively managing blood pressure.<span class="citation" data-cites="citation2"><sup>[<a href="#ref-citation2" role="doc-biblioref">2</a>]</sup></span> The fact that these statistically derived importance scores align perfectly with established clinical understanding, where hypertension and age are known high-risk factors<span class="citation" data-cites="citation12"><sup>[<a href="#ref-citation12" role="doc-biblioref">8</a>]</sup></span>, strengthens the trust necessary for model deployment in high-stakes healthcare environments.<span class="citation" data-cites="citation20"><sup>[<a href="#ref-citation20" role="doc-biblioref"><strong>citation20?</strong></a>]</sup></span></p>
</section>
<section id="comparative-performance-and-the-argument-for-simplicity" class="level2">
<h2 class="anchored" data-anchor-id="comparative-performance-and-the-argument-for-simplicity">5.2. Comparative Performance and the Argument for Simplicity</h2>
<p>While the LR model demonstrated robust discrimination (AUROC 0.725), it is acknowledged that other, more complex machine learning approaches have achieved numerically higher AUROC values in comparable studies.<span class="citation" data-cites="citation26"><sup>[<a href="#ref-citation26" role="doc-biblioref">15</a>]</sup></span> However, this study strategically prioritizes LR based on established principles in medical informatics.</p>
<p>Firstly, evidence suggests that the practical benefits of advanced ML models, such as deep learning, only significantly emerge when the models are trained on sample sizes several magnitudes larger than conventional clinical datasets.<span class="citation" data-cites="citation29"><sup>[<a href="#ref-citation29" role="doc-biblioref"><strong>citation29?</strong></a>]</sup></span> When the feature space is limited (11 clinical variables) and the sample size is moderate, the increased mathematical complexity of advanced ML models often does not translate into superior performance upon external validation, as indicated by systematic reviews.<span class="citation" data-cites="citation28"><sup>[<a href="#ref-citation28" role="doc-biblioref">16</a>]</sup></span> In fact, linear models have been shown to outperform complex models on small datasets.<span class="citation" data-cites="citation29"><sup>[<a href="#ref-citation29" role="doc-biblioref"><strong>citation29?</strong></a>]</sup></span></p>
<p>Secondly, model reliability, measured through calibration, is frequently a stronger performance indicator for clinical deployment than raw discriminatory power (AUROC).<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> LR models often demonstrate good calibration, ensuring that a predicted probability (e.g., 20% risk) accurately reflects the observed incidence rate in that risk cohort.<span class="citation" data-cites="citation28"><sup>[<a href="#ref-citation28" role="doc-biblioref">16</a>]</sup></span> Furthermore, complex models introduce methodological challenges, such as difficulties in thoughtful model specification and criticism, especially when integrating multiple data sources.<span class="citation" data-cites="citation34"><sup>[<a href="#ref-citation34" role="doc-biblioref"><strong>citation34?</strong></a>]</sup></span> For generalizable primary prevention models, prioritizing an interpretable model with reliable calibration over marginal gains in AUROC is a defensible clinical strategy.</p>
</section>
<section id="ethical-implications-bias-and-fairness" class="level2">
<h2 class="anchored" data-anchor-id="ethical-implications-bias-and-fairness">5.3. Ethical Implications, Bias, and Fairness</h2>
<p>The application of predictive modeling in healthcare carries significant ethical obligations, particularly regarding bias and fairness.<span class="citation" data-cites="citation35"><sup>[<a href="#ref-citation35" role="doc-biblioref">20</a>]</sup></span> Systemic biases in model outputs can originate from imbalanced training data, which leads to the underrepresentation of certain patient groups and potentially results in inequitable healthcare access or outcomes.<span class="citation" data-cites="citation35"><sup>[<a href="#ref-citation35" role="doc-biblioref">20</a>]</sup></span></p>
<p>The decision to address the dataset’s severe class imbalance through sampling techniques during the methodology phase was critical not just for statistical performance (improving sensitivity and AUPRC) but for addressing potential fairness concerns. Failure to accurately classify the minority (stroke) class results in high false negative rates, which could disproportionately affect specific subgroups if the model learned to ignore their subtle risk cues. While bias refers to systematic errors in model development, fairness is concerned with how equitably the model performs across different demographic groups.<span class="citation" data-cites="citation35"><sup>[<a href="#ref-citation35" role="doc-biblioref">20</a>]</sup></span></p>
<p>Future development must move beyond overall performance parity (like aggregate AUROC) to evaluate specific fairness criteria, such as <strong>equalized odds</strong> or <strong>predictive rate parity</strong>.<span class="citation" data-cites="citation36"><sup>[<a href="#ref-citation36" role="doc-biblioref"><strong>citation36?</strong></a>]</sup></span> These criteria ensure that the error rates (false positives and false negatives) or predictive values are equitable across critical subgroups (e.g., by gender or race). The inherent interpretability of LR simplifies this ethical auditing process, as coefficients can be directly scrutinized for potential demographic weighting, which is significantly more challenging in opaque ML models.<span class="citation" data-cites="citation20"><sup>[<a href="#ref-citation20" role="doc-biblioref"><strong>citation20?</strong></a>]</sup></span> Transparency and generalizability, ensuring the model accounts for data from diverse patient populations, are fundamental ethical guardrails for AI in stroke research.<span class="citation" data-cites="citation19"><sup>[<a href="#ref-citation19" role="doc-biblioref"><strong>citation19?</strong></a>]</sup></span></p>
</section>
<section id="limitations-and-future-research-directions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-research-directions">5.4. Limitations and Future Research Directions</h2>
<p>This study is subject to several limitations. First, the model was validated solely using an internal test set derived from the same source population. As demonstrated in comparative literature, models often underperform when assessed in independent, external validation datasets due to reduced transportability.@citation28 Second, the feature set was restricted to 11 common clinical variables. More advanced risk prediction may be possible by integrating supplementary data, such as detailed physical activity metrics or neuroimaging-derived measures like lesion location.<span class="citation" data-cites="citation10"><sup>[<a href="#ref-citation10" role="doc-biblioref">6</a>]</sup></span> The omission of key factors related to acute stroke management or patient preferences for rehabilitation also limits the model’s scope for predicting functional recovery outcomes.<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> Furthermore, as a linear model, LR cannot capture non-linear interactions or highly complex epidemiological relationships between risk factors.<span class="citation" data-cites="citation34"><sup>[<a href="#ref-citation34" role="doc-biblioref"><strong>citation34?</strong></a>]</sup></span></p>
<p>Future research should focus on three primary areas. First, external validation of this LR model is necessary to confirm its generalizability across different clinical sites and populations. Second, comparative studies should prioritize clinical utility metrics—specifically Decision Curve Analysis (DCA) and detailed Calibration—to objectively assess whether non-linear ML models offer tangible clinical net benefits over simpler, more interpretable models like LR.<span class="citation" data-cites="citation16"><sup>[<a href="#ref-citation16" role="doc-biblioref"><strong>citation16?</strong></a>]</sup></span> Third, future predictive modeling efforts must integrate rigorous fairness-aware validation, ensuring equalized error rates across defined patient subgroups to support safe and equitable deployment in real-world healthcare settings.<span class="citation" data-cites="citation35"><sup>[<a href="#ref-citation35" role="doc-biblioref">20</a>]</sup></span></p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>6. Conclusion</h1>
<p>The Logistic Regression model developed and validated in this study offers a robust, highly interpretable, and reproducible tool for stroke risk stratification using standardized clinical predictors. The model successfully quantified the independent risks associated with core factors, confirming that Age and Hypertension are the most significant drivers of stroke probability, providing the results in the form of clear, clinically actionable Odds Ratios. While complex machine learning methods continue to push boundaries in performance metrics, the transparency and reliable calibration of Logistic Regression ensure its critical role in clinical prediction. By executing the analysis through a transparent Quarto workflow, this research advocates for reproducibility as a mandatory standard in medical informatics. Ultimately, the simplicity and interpretability of LR enhance clinician trust and facilitate the direct application of personalized risk information, which is essential for guiding primary prevention strategies and improving public health outcomes.</p>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-citation1" class="csl-entry" role="listitem">
1. World Health Organization, &amp; Fedesoriano. (2022). <em><span class="nocase">Stroke Prediction Dataset and Global Burden Statistics</span></em>. Kaggle Dataset and WHO Statistics. <a href="https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset">https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</a>
</div>
<div id="ref-citation2" class="csl-entry" role="listitem">
2. Boehme, A., Esenwa, C., &amp; Elkind, M. (2017). Stroke: A global health crisis. <em>Circulation Research</em>, <em>123</em>(4), 459–471.
</div>
<div id="ref-citation4" class="csl-entry" role="listitem">
3. Wang, L. (2023). Logistic regression for stroke prediction: An evaluation of its accuracy and validity. <em>International Journal of Advanced Medical Informatics</em>, <em>15</em>(2), 112–125.
</div>
<div id="ref-citation5" class="csl-entry" role="listitem">
4. Steyerberg, E., Moons, K., &amp; Van Calster, B. (2025). The role of logistic regression in clinical prediction: A narrative review. <em>Academic Medicine and Surgery</em>, <em>2</em>(1), 10001–10015.
</div>
<div id="ref-citation7" class="csl-entry" role="listitem">
5. Allaire, J., &amp; Yihui, X. (2024). Quarto: Publishable scientific and technical documents. <em>Journal of Statistical Software</em>, <em>109</em>(1), 1–25.
</div>
<div id="ref-citation10" class="csl-entry" role="listitem">
6. Liu, T., Hu, M., &amp; Wang, Y. (2025). Machine learning algorithms for stroke risk prediction: A comprehensive evaluation. <em>Frontiers in Neurology</em>, <em>16</em>, 1668420.
</div>
<div id="ref-citation11" class="csl-entry" role="listitem">
7. Chen, S., Liu, Y., &amp; Zhang, L. (2024). Comparison of machine learning models for predicting stroke risk in hypertensive patients. <em>BMC Cardiovascular Disorders</em>, <em>24</em>, 305.
</div>
<div id="ref-citation12" class="csl-entry" role="listitem">
8. Sun, W., Liu, M., &amp; Li, S. (2021). Feature ranking and risk analysis for stroke prediction using machine learning. <em>IEEE Access</em>, <em>9</em>, 78901–78913.
</div>
<div id="ref-citation14" class="csl-entry" role="listitem">
9. Buongiorno, R., Caudai, C., Colantonio, S., &amp; Germanese, D. (2024). Integrating AI in personalized disease management: New trends in medical informatics. <em>Proceedings of the International Conference on Health Informatics</em>, 112–120.
</div>
<div id="ref-citation15" class="csl-entry" role="listitem">
10. Luo, W., Ye, H., &amp; Zou, T. (2024). Guidelines for developing and reporting machine learning predictive models in biomedical research: A multidisciplinary view. <em>Journal of Medical Internet Research</em>, <em>26</em>(1), e50890.
</div>
<div id="ref-citation17" class="csl-entry" role="listitem">
11. Wu, Y., Chen, M., &amp; Li, H. (2023). Machine learning algorithms for stroke risk prediction: A review of feature selection and model performance. <em>Medical Informatics and Decision Making</em>, <em>23</em>(1), 304.
</div>
<div id="ref-citation18" class="csl-entry" role="listitem">
12. Holzinger, A., Keil, P., &amp; Kappel, M. (2024). Explainable AI (XAI) in healthcare: A review of opportunities and challenges. <em>Artificial Intelligence in Medicine</em>, <em>150</em>, 102875.
</div>
<div id="ref-citation23" class="csl-entry" role="listitem">
13. Zou, T., He, Q., &amp; Liu, M. (2023). Performance metrics for imbalanced classification in medical diagnosis: Moving beyond accuracy. <em>Diagnostics</em>, <em>13</em>(15), 2590.
</div>
<div id="ref-citation22" class="csl-entry" role="listitem">
14. McHugh, M. (2013). Logistic regression: The procedure, interpretation, and application. <em>Journal of Biostatistics and Epidemiology</em>, <em>4</em>(2), 167–172.
</div>
<div id="ref-citation26" class="csl-entry" role="listitem">
15. Wang, Y., Li, H., &amp; Chen, G. (2022). Predicting stroke outcome: Comparison of generalized regression neural network and logistic regression. <em>International Journal of Medical Sciences</em>, <em>19</em>(5), 800–807.
</div>
<div id="ref-citation28" class="csl-entry" role="listitem">
16. Jelmer, M., Wynants, L., &amp; Van Calster, B. (2019). A systematic review shows no performance benefit of machine learning over logistic regression for clinical prediction models. <em>Journal of Clinical Epidemiology</em>, <em>110</em>, 12–22.
</div>
<div id="ref-citation6" class="csl-entry" role="listitem">
17. Shah, J. (2021). <em>Stroke prediction using logistic regression</em>. Kaggle Notebook. <a href="https://www.kaggle.com/code/js1312/stroke-prediction-using-logistic-regression">https://www.kaggle.com/code/js1312/stroke-prediction-using-logistic-regression</a>
</div>
<div id="ref-citation8" class="csl-entry" role="listitem">
18. Al-Shaykh, A., Alghazawi, M., &amp; Al-Haddad, R. (2024). Addressing class imbalance in stroke prediction: A comparative analysis of sampling techniques. <em>Journal of Biomedical Informatics</em>, <em>149</em>, 104543.
</div>
<div id="ref-citation33" class="csl-entry" role="listitem">
19. Gao, Y., Zhang, L., &amp; Li, Q. (2025). SHAP analysis reveals the dominance of clinical comorbidities in postoperative stroke prediction. <em>Journal of Surgical Research</em>, <em>301</em>, 112–120.
</div>
<div id="ref-citation35" class="csl-entry" role="listitem">
20. Gichoya, J., Many, J., &amp; Zafar, A. (2025). Bias and fairness in patient-level prediction models: Ethical and technical challenges. <em>Journal of the American Medical Informatics Association Open</em>, <em>8</em>(5), ooaf115.
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/renanmb\.github\.io\/IDC-6940---Capstone-Project-Fall-2025\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>