{
  "hash": "8d163c48be7ea052757d7bfc6a846ae5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Draft v06 --- Predicting stroke risk from common health indicators: a binary logistic regression analysis\"\ndescription: \"Shree sent back draft with changes\"\nauthor:\n  - name: Renan Monteiro Barbosa\n    url: https://github.com/renanmb\n    affiliation: Master of Data Science Program @ The University of West Florida (UWF)\n  - name: \"Shree Krishna M.S Basnet\"\n  - name: \"Supervisor: Dr. Cohen\"\n# date: 10-24-2022\ncategories: [draft, renan]\n# citation:\n#   url: https://samanthacsik.github.io/posts/2022-10-24-my-blog-post/\nimage: images/spongebob-imagination.jpg\ndraft: false\nbibliography: references.bib\nlink-citations: true\n---\n\n<!-- \"Predicting stroke risk from common health indicators: a binary logistic regression analysis\"\n- \"Shree Krishna M.S Basnet\"\n- \"Renan\"\n- \"Supervisor: Dr. Cohen\" -->\n\n\n\n\n\n# Introduction\n\nStroke affects people all around the world, resulting in numerous deaths and disabilities.  [@WHO2025]. If we are able to detection stroke early for those at increased risk is will be amazing for prevention and prompt intervention because stroke frequently happens quickly and can cause long-term neurological disability.  Clinicians and public health experts can measure individual-level risk and target high-risk populations for clinical management and lifestyle counseling by using data-driven risk prediction models.\n\nLogistic Regression (LR) is one of the most widely used approaches for modelling binary outcomes such as disease is present in human or not  [@sperandei2014understanding]. It extends linear regression to cases where the outcome is categorical and provides interpretable coefficients and odds ratios that describe how each predictor is associated with the probability of the event. LR has been applied across a wide range of domains, including child undernutrition and anaemia [@asmare2024determinants], road traffic safety [@rahman2021identification; @chen2024binary; @chen2020modeling], health-care utilisation and clinical admission decisions [@hutchinson2023predictors], and fraud detection [@samara2024using]. These applications highlight both the flexibility of LR and its suitability for real-world decision-making problems.\n\nIn this project, we analyse a publicly available stroke dataset that includes key demographic, behavioural, and clinical predictors such as age, gender, hypertension status, heart disease, marital status, work type, residence type, smoking status, body mass index (BMI), and average glucose level. These variables are commonly reported in the stroke and cardiovascular literature as important determinants of risk. Using this dataset, we first clean and recode the variables into appropriate numeric formats and then develop a series of supervised learning models for stroke prediction.\n\nLogistic Regression is used as the primary, interpretable baseline model, but its performance is compared against several more complex machine-learning techniques, including Decision Tree, Random Forest, Gradient Boosted Machine, k-Nearest Neighbours, and Support Vector Machine (radial). Model performance is evaluated using accuracy, sensitivity, specificity, ROC curves, AUC, and confusion matrices. The main objectives are to identify the most influential predictors of stroke and to determine whether advanced machine-learning models offer meaningful improvements over Logistic Regression for classification of stroke risk in this dataset.\n\n# Methodology\n\nThis part explains about our stoke dataset, variables, preprocessing steps, logistic regression formulation, and the machine-learning modelling framework used to compare classifiers.\n\nOur datset contains 5,110 observations and 11 predictors commonly associated with cerebrovascular risk. After cleaning missing and inconsistent entries (e.g., “Unknown”, “N/A”, or rare textual categories such as “children” and “other”), a final dataset of 3,357 individuals remained for analysis. The cleaned dataset is stored in the object **strokeclean**.\n\nRespose we get is in binary so logestic regression is the best approach to observe whether the patient has had **stroke=1** or not **stroke=0** [@hosmer2013applied; @james2021isl]\n\n**Variables**\n\nThe key predictors are listed below.\n\n| Variable              | Type                           | Description                   |\n| --------------------- | ------------------------------ | ----------------------------- |\n| **age**               | Numeric                        | Age of the individual (years) |\n| **gender**            | Categorical (1=Male, 2=Female) | Biological sex                |\n| **hypertension**      | Binary (0/1)                   | Prior hypertension diagnosis  |\n| **heart_disease**     | Binary (0/1)                   | Presence of heart disease     |\n| **ever_married**      | Binary                         | Marital status                |\n| **work_type**         | Categorical (1–4)              | Employment category           |\n| **Residence_type**    | Binary (1=Urban, 2=Rural)      | Place of residence            |\n| **smoking_status**    | Categorical                    | Never/Former/Smokes           |\n| **bmi**               | Numeric                        | Body Mass Index               |\n| **avg_glucose_level** | Numeric                        | Average glucose level         |\n| **stroke**            | Binary outcome (0=No, 1=Yes)   | Stroke occurrence             |\n\nStroke is a highly unbalanced outcome variable:\n- Yes (stroke): about 5%\n- No (no stroke): around 95%\n\nBecause it is possible to achieve high overall accuracy by merely forecasting the majority class, this class imbalance directly affects model evaluation. Because of this, in addition to accuracy, we also concentrate on sensitivity, specificity, ROC curves, AUC, and Youden's J statistic.\n\n**Dataset Prepration**\nTo guarantee model validity and stop data leakage, data preprocessing is performed. [@wang2014].\n\nAmong the steps were:\n\n- Elimination of non-predictive identifiers (patient ID)\n\n- Transforming categorical variables into dummy numerical representations\n\n- Managing uncommon or irregular categories (e.g., \"Other\" gender values handled as absent)\n\n- BMI, glucose, and age conversion to numerical\n\n- Rows with unintelligible labels (\"Unknown,\" \"N/A\") are removed.\n\n- Valid range and consistency verification\n\n- After recoding, missing values might be imputed or removed.\n\n- During splitting, stratified sampling is used to maintain the stroke/no-stroke ratio [@chen2020modeling].\n\n- The outcome stroke was defined as a factor with levels \"No\" and \"Yes\" in the cleaned dataset strokeclean.\n\nTo check sample performance, the data were split into training and test sets. For the baseline logistic regression model, a simple random 70/30 split was used. For the full machine-learning comparison, a stratified partition (via caret::createDataPartition) was applied to preserve the stroke/no-stroke ratio in both sets.\n\n**Logistic regression model **\n\nLet $Y_i$ denote the stroke status for patient $i$, where\n\n- $Y_i = 1$ if patient $i$ experienced a stroke  \n- $Y_i = 0$ otherwise.\n\nLet the predictor vector for patient $i$ be\n\n$$\n\\mathbf{x}_i = (x_{i1}, x_{i2}, \\ldots, x_{ip})^\\top,\n$$\n\nwhere the $p$ predictors such as age, hypertension, heart disease, average glucose level, BMI, and smoking status. \n\nThe logistic regression model specifies the conditional probability of stroke as\n\n\n\n$$\nP(Y_i = 1 \\mid \\mathbf{x}_i)\n= \\pi(\\mathbf{x}_i)\n= \\frac{\\exp\\big(\\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_p x_{ip}\\big)}\n       {1 + \\exp\\big(\\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_p x_{ip}\\big)}.\n$$\n\nEquivalently, the logit (log-odds) of stroke is modeled as a linear combination of the predictors:\n\n$$\n\\log\\left(\\frac{\\pi(\\mathbf{x}_i)}{1 - \\pi(\\mathbf{x}_i)}\\right)\n  = \\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_p x_{ip}.\n$$\n\nHere, $\\beta_0$ is the intercept, $\\beta_j$ is the change in log-odds of stroke for a one-unit increase in predictor \n $x_j$, holding other variables constant.\n\nExponentiating $\\beta_j$ gives the odds ratio (OR):\n$$\n\\text{OR}_j = e^{\\beta_j},\n$$\n\n\nwhich represents the multiplicative change in the odds of stroke for a one-unit increase in $x_j$.\n\n**Model Estimation**\n\nLet $\\boldsymbol{\\beta} = (\\beta_0, \\beta_1, \\ldots, \\beta_p)^\\top$ denote the vector of\nregression coefficients. For independent observations, the likelihood of the data is\n$$\nL(\\boldsymbol{\\beta})\n= \\prod_{i=1}^{n}\n  \\pi(\\mathbf{x}_i)^{\\,y_i}\n  \\left[1 - \\pi(\\mathbf{x}_i)\\right]^{\\,1-y_i},\n$$\n\nwhere $\\pi(\\mathbf{x}_i) = P(Y_i = 1 \\mid \\mathbf{x}_i)$.\n\nThe **log-likelihood**   is\n\n$$\n\\ell(\\boldsymbol{\\beta})\n= \\sum_{i=1}^{n}\n\\left[\n  y_i \\log\\big(\\pi(\\mathbf{x}_i)\\big)\n  +\n  (1 - y_i)\\log\\big(1 - \\pi(\\mathbf{x}_i)\\big)\n\\right].\n$$\n\nThe maximum likelihood estimate $\\hat{\\boldsymbol{\\beta}}$ is the value of\n$\\boldsymbol{\\beta}$ that maximizes $\\ell(\\boldsymbol{\\beta})$. In R, this optimization\nis carried out automatically using `glm(..., family = binomial)`\n\n\n\n**Machine learning models and evaluation**\n\nSix supervised models were fitted using the caret framework in order to determine whether more sophisticated methods may significantly enhance stroke classification:\n\n- Logistic Regression (LR)\n\n- Decision Tree (rpart)\n\n- Random Forest (RF)\n\n- Gradient Boosted Machine (GBM)\n\n- k-Nearest Neighbours (k-NN)\n\n- Support Vector Machine with radial kernel (SVM-Radial)\n\nAll models used the same 70% training / 30% test split and a consistent cross-validation procedure to ensure fair comparison.\nTo guarantee a fair comparison, all models employed the same cross-validation process and a 70% training/30% test split.\n\n\n**Data Splitting and Model Fitting in R**\n\nThe cleaned dataset is stored in the object `strokeclean`, where the outcome variable is\n`stroke` (0 = No stroke, 1 = Stroke), and predictors include `age`, `hypertension`,\n`heart_disease`, `avg_glucose_level`, `bmi`, `smoking_status`, and others.\n\nFirst, the dataset is randomly divided into a training set (70%) and a test set (30%) to\nevaluate out-of-sample performance, logistic regression model is then fitted on the training data:\n\n\nFrom this model, estimated odds ratios and 95% confidence intervals are computed as:\n\n\n\n**Model Predictions and Performance Measures**\n\nPredicted probabilities on the test set are obtained as:\n\n\nUsing a classification threshold $c = 0.5$, the predicted class for patient $i$ is\n\n$$\n\\hat{y}_i =\n\\begin{cases}\n1, & \\text{if } \\hat{\\pi}_i \\ge c, \\\\\\\\\n0, & \\text{if } \\hat{\\pi}_i < c.\n\\end{cases}\n$$\n\nwhere $\\hat{\\pi}_i$ is the predicted probability of stroke for patient $i$.\n\n\n**Evaluation Metrics**\n\nModels were evaluated using standard clinical classification metrics:\n\n- Accuracy\n\n- Sensitivity (Recall)\n\n- Specificity\n\n- Precision\n\n- F1-Score\n\n- Receiver Operating Characteristic (ROC) curve\n\n- Area Under the Curve (AUC)\n\nYouden’s J Statistic, Used to determine optimal classification threshold:\n\n$J = \\text{Sensitivity} + \\text{Specificity} - 1$\n\n\nThese metrics are widely used in stroke-risk modeling literature and as per article it is often used to find optimial classidfication threshhold. [@chen2020modeling].\n\n\n\n# Analysis\n\nBefore starting to generate predictive models, an exploratory analysis was conducted to understand the distribution, structure, and relationships within the cleaned dataset (N = 3,357). This step is crucial in rare-event medical modeling because data imbalance, skewed predictors, or correlated variables can directly influence model behavior and classification performance.\n\n\n**Distribution of Key Continuous Variables**\n\nHistograms were used to assess the spread of the primary numeric predictors (Age, BMI, and Average Glucose Level). These variables demonstrate clinically expected right-skewness, particularly glucose and BMI, consistent with published literature on metabolic and cardiovascular risk distributions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histograms for key numeric variables\nlibrary(ggplot2)\n\np_age  = ggplot(strokeclean, aes(age)) + geom_histogram(binwidth=5, fill=\"green\") +\n  labs(title=\"Age Distribution\", x=\"Age\", y=\"Count\")\n\np_bmi  = ggplot(strokeclean, aes(bmi)) + geom_histogram(binwidth=2, fill=\"pink\") +\n  labs(title=\"BMI Distribution\", x=\"BMI\", y=\"Count\")\n\np_gluc = ggplot(strokeclean, aes(avg_glucose_level)) + \n  geom_histogram(binwidth=10, fill=\"yellow\") +\n  labs(title=\"Average Glucose Level\", x=\"Glucose Level\", y=\"Count\")\n\nggpubr::ggarrange(p_age, p_bmi, p_gluc, ncol=3)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nOur histograms is generating valuable variation of primary numerical predictors.\n\n- Age is distributed with phase of life mainly from teenage till old age, with most individuals concentrated between 40–70 years, reflecting a typical mid-to-older population where stroke risk naturally increases.\n\n- BMI displays a moderately right-skewed pattern, with most values falling between 22–35, consistent with a population where overweight status is common but extreme obesity is rare.\n\n- The average glucose level is substantially skewed to the right, with many people having glucose levels below 120 but a large tail that extends beyond 200, suggesting the presence of people with metabolic problems or possibly diabetes, which is a significant clinical risk factor for stroke.\n\nWhen combined, these distributions show common clinical trends and offer a strong basis for predictive modeling.\n\n\n**Distribution of Key Categorical Variables**\n\nBar charts help visualize population composition. The dataset shows more females than males, a balanced rural–urban distribution, and substantial variation in work type and smoking behavior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bar charts for categorical variables\n\n# Fix labels for plotting only\n\n# Gender: 1 = Male, 2 = Female\nstrokeclean$gender = factor(\n  strokeclean$gender,\n  levels = c(1, 2),\n  labels = c(\"Male\", \"Female\")\n)\n\n# Smoking status: 1 = Never, 2 = Formerly, 3 = Smokes\nstrokeclean$smoking_status = factor(\n  strokeclean$smoking_status,\n  levels = c(1, 2, 3),\n  labels = c(\"Nsmoked\", \"Fsmoked\", \"Smokes\")\n)\n\n# Residence type: 1 = Urban, 2 = Rural\nstrokeclean$Residence_type = factor(\n  strokeclean$Residence_type,\n  levels = c(1, 2),\n  labels = c(\"Urban\", \"Rural\")\n)\n\n\np_gender = ggplot(strokeclean, aes(gender)) + geom_bar(fill=\"red\") +\nlabs(title=\"Gender Distribution\", x=\"G\", y=\"Count\")\n\np_smoke = ggplot(strokeclean, aes(smoking_status)) + geom_bar(fill=\"blue\") +\nlabs(title=\"Smoking Status\", x=\"S\", y=\"Count\")\n\np_res = ggplot(strokeclean, aes(Residence_type)) + geom_bar(fill=\"green\") +\nlabs(title=\"Residence Type\", x=\"R\", y=\"Count\")\n\nggpubr::ggarrange(p_gender, p_smoke, p_res, ncol=3)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nBar plots were created to visualize demographic and behavioral attributes.\n\n- Gender: Females account for a significantly bigger proportion of the sample than males, which may influence overall stroke estimates and must be addressed when interpreting model results.\n\n- Smoking status shows a large “never smoked” group\n\n- Residence Type: Urban and rural residents are almost evenly represented, suggesting a balanced dataset with respect to geographical living conditions\n\nOverall, these distributions show that the dataset includes a diverse mix of demographic and lifestyle categories, helping ensure that the predictive models capture variation across different subpopulations.\n\n\n**Correlation among key numeric prediators**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumeric_vars = strokeclean[, c(\"age\", \"bmi\", \"avg_glucose_level\",\n\"hypertension\", \"heart_disease\")]\n\ncorr_matrix = cor(numeric_vars)\n\nggcorrplot::ggcorrplot(\n  corr_matrix,\n  lab = TRUE,\n  colors = c(\"purple\", \"gold\", \"grey\"),\n  title = \"Correlation Heatmap of Key Predictors\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThe correlation heatmap shows that relationships among the key predictors are generally weak to moderate, indicating low multicollinearity and confirming that these variables can be safely used together in a logistic regression model.\n\n- Age, hypertension, and heart disease all have small positive connections (about 0.24-0.26), which is to be expected given that cardiovascular problems tend to worsen as people age.\n\n- The average glucose level displays minor positive associations with age and hypertension, indicating known metabolic risk patterns.\n\n- BMI shows almost no correlation with the other predictors, suggesting it contributes unique information.\n\n- No correlation values approach levels that would threaten model stability (e.g., > 0.7).\n\nOverall, the predictors are reasonably independent, supporting their combined use in further statistical and machine-learning models.\n\n**Stroke rates for key risk factors**\n\nHypertension and stroke\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strokeclean, aes(x = hypertension, fill = stroke)) +\ngeom_bar(position = \"fill\") +\nscale_y_continuous(labels = scales::percent) +\nlabs(\ntitle = \"Stroke Rate by Hypertension Status\",\nx     = \"Hypertension (0 = No, 1 = Yes)\",\ny     = \"Percentage\"\n) +\nscale_fill_manual(values = c(\"No\" = \"yellow\", \"Yes\" = \"red\")) +\ntheme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nHypertensive individuals have a noticeably higher percentage of stroke events compared with non-hypertensive individuals, reinforcing hypertension as a major modifiable risk factor.\n\n**Heart disease and stroke**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strokeclean, aes(x = heart_disease, fill = stroke)) +\ngeom_bar(position = \"fill\") +\nscale_y_continuous(labels = scales::percent) +\nlabs(\ntitle = \"Stroke Rate by Heart Disease\",\nx     = \"Heart Disease (0 = No, 1 = Yes)\",\ny     = \"Percentage\"\n) +\nscale_fill_manual(values = c(\"No\" = \"pink\", \"Yes\" = \"green\")) +\ntheme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nIndividuals with heart disease show substantially higher stroke rates than those without heart disease, consistent with clinical understanding that cardiovascular disease and stroke share many underlying mechanisms.\n\n**Smoking status and stroke**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strokeclean, aes(x = smoking_status, fill = stroke)) +\ngeom_bar(position = \"fill\") +\nscale_y_continuous(labels = scales::percent) +\nlabs(\ntitle = \"Stroke Rate by Smoking Behavior\",\nx     = \"1 = Never, 2 = Former, 3 = Smokes\",\ny     = \"Percentage\"\n) +\nscale_fill_manual(values = c(\"No\" = \"grey70\", \"Yes\" = \"red\")) +\ntheme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nBoth former and current smokers exhibit higher stroke percentages than never-smokers, illustrating the lasting impact of smoking on vascular risk. This supports public health messages around smoking cessation and risk reduction.\n\n\n.\n**Baseline logistic regression model**\n\n- Train/test split and model fitting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\nn <- nrow(strokeclean)\ntrain_index <- sample(seq_len(n), size = 0.7 * n)\n\nstroke_train <- strokeclean[train_index, ]\nstroke_test  <- strokeclean[-train_index, ]\n\nfit_glm <- glm(\nstroke ~ age + hypertension + heart_disease +\navg_glucose_level + bmi + smoking_status +\ngender + ever_married,\ndata   = stroke_train,\nfamily = binomial(link = \"logit\")\n)\n\nsummary(fit_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = stroke ~ age + hypertension + heart_disease + avg_glucose_level + \n    bmi + smoking_status + gender + ever_married, family = binomial(link = \"logit\"), \n    data = stroke_train)\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -8.459296   0.898462  -9.415   <2e-16 ***\nage                    0.072640   0.008172   8.889   <2e-16 ***\nhypertension           0.455371   0.229016   1.988   0.0468 *  \nheart_disease          0.487364   0.270854   1.799   0.0720 .  \navg_glucose_level      0.003777   0.001707   2.213   0.0269 *  \nbmi                    0.006537   0.015715   0.416   0.6774    \nsmoking_statusFsmoked  0.233821   0.227332   1.029   0.3037    \nsmoking_statusSmokes   0.468664   0.266313   1.760   0.0784 .  \ngenderFemale           0.230554   0.207568   1.111   0.2667    \never_married           0.118482   0.311089   0.381   0.7033    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 953.42  on 2348  degrees of freedom\nResidual deviance: 776.77  on 2339  degrees of freedom\nAIC: 796.77\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n:::\n\n\nThe model includes age, hypertension, heart disease, average glucose level, BMI, smoking status, gender, and marital status as predictors.\n\n**Odds ratios and confidence intervals**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Odds ratios and 95% confidence intervals\n\ncoef_est <- coef(fit_glm)\nOR       <- exp(coef_est)\n\nconf_int <- exp(confint(fit_glm))  # confidence intervals on OR scale\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWaiting for profiling to be done...\n```\n\n\n:::\n\n```{.r .cell-code}\nodds_table <- cbind(OR, conf_int)\ncolnames(odds_table) <- c(\"OR\", \"2.5 %\", \"97.5 %\")\nround(odds_table, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         OR 2.5 % 97.5 %\n(Intercept)           0.000 0.000  0.001\nage                   1.075 1.059  1.093\nhypertension          1.577 0.996  2.450\nheart_disease         1.628 0.942  2.733\navg_glucose_level     1.004 1.000  1.007\nbmi                   1.007 0.975  1.037\nsmoking_statusFsmoked 1.263 0.806  1.969\nsmoking_statusSmokes  1.598 0.938  2.674\ngenderFemale          1.259 0.842  1.903\never_married          1.126 0.590  2.013\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\nThe logistic regression findings demonstrate how each predictor impacts the likelihood of having a stroke, while keeping other variables constant:\n\n- Age (OR = 1.075, CI: 1.059–1.093)\nAge is the strongest continuous predictor. Each additional year of age increases the odds of stroke by about 7.5%, and the confidence interval does not include 1, indicating strong statistical significance.\n\n- Hypertension (OR = 1.577, CI: 0.996–2.450)\nIndividuals with hypertension have roughly 58% higher odds of stroke compared to those without hypertension, although the lower CI bound is just below 1. This suggests a borderline significant effect, but clinically important.\n\n- Heart disease (OR = 1.628, CI: 0.942–2.733)\nHeart disease increases stroke odds by about 63%, but the CI includes 1, implying the association is positive but not statistically strong in this dataset.\n\n- Average glucose level (OR = 1.004, CI: 1.000–1.007)\nHigher glucose levels are associated with slightly increased stroke risk. Though the effect is small, the CI indicates marginal significance, aligning with known metabolic risk patterns.\n\n- BMI (OR = 1.007, CI: 0.975–1.037)\nBMI shows almost no meaningful effect on stroke risk, and the CI overlaps 1. This predictor does not significantly influence stroke likelihood in this dataset.\n\n- Smoking (Fsmoked OR = 1.263; Smokes OR = 1.598)\n\n- Former smokers have 26% higher odds, but CI crosses 1 → weak evidence.\n\n- Current smokers have ~60% higher odds, but CI still overlaps 1 → suggests increased risk but not statistically conclusive here.\n\n- Gender (Female) (OR = 1.259; CI: 0.842–1.903)\nFemales show slightly higher odds, but this effect is not statistically significant.\n\n- Ever married (OR = 1.126; CI: 0.590–2.013)\nMarital status has no clear effect on stroke odds in this sample.\n\n\n\n\n**Model predictions and performance on the test set**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(caret)\n\n# 1) Predicted probabilities from logistic regression\nstroke_test$pred_prob <- predict(\n  fit_glm,\n  newdata = stroke_test,\n  type    = \"response\"\n)\n\n# 2) Make sure the TRUE outcome is a factor with levels No / Yes\nstroke_test$stroke <- factor(stroke_test$stroke,\n                             levels = c(\"No\", \"Yes\"))\n\n# 3) Class predictions at threshold c = 0.5\nstroke_test$pred_class <- ifelse(stroke_test$pred_prob >= 0.5, \"Yes\", \"No\")\nstroke_test$pred_class <- factor(stroke_test$pred_class,\n                                 levels = c(\"No\", \"Yes\"))\n\n# 4) Confusion matrix: positive = \"Yes\"\ncm <- confusionMatrix(\n  data      = stroke_test$pred_class,\n  reference = stroke_test$stroke,\n  positive  = \"Yes\"\n)\n\ncm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction  No Yes\n       No  949  58\n       Yes   0   1\n                                         \n               Accuracy : 0.9425         \n                 95% CI : (0.9262, 0.956)\n    No Information Rate : 0.9415         \n    P-Value [Acc > NIR] : 0.4811         \n                                         \n                  Kappa : 0.0314         \n                                         \n Mcnemar's Test P-Value : 7.184e-14      \n                                         \n            Sensitivity : 0.0169492      \n            Specificity : 1.0000000      \n         Pos Pred Value : 1.0000000      \n         Neg Pred Value : 0.9424032      \n             Prevalence : 0.0585317      \n         Detection Rate : 0.0009921      \n   Detection Prevalence : 0.0009921      \n      Balanced Accuracy : 0.5084746      \n                                         \n       'Positive' Class : Yes            \n                                         \n```\n\n\n:::\n:::\n\n\nFrom the confusion matrix, the following performance metrics are defined:\n\n**Accuracy**\n$$\n\\text{Accuracy} =\n\\frac{TP + TN}{TP + TN + FP + FN}.\n$$\n**Sensitivity (Recall / True Positive Rate)**\n\n$$\n\\text{Sensitivity} =\n\\frac{TP}{TP + FN}.\n$$\n**Specificity (True Negative Rate)**\n\n$$\n\\text{Specificity} =\n\\frac{TN}{TN + FP}.\n$$\n\n**Positive Predictive Value (Precision)**\n$$\n\\text{PPV} =\n\\frac{TP}{TP + FP}.\n$$\n**Negative Predictive Value (NPV)**\n\n$$\n\\text{NPV} =\n\\frac{TN}{TN + FN}.\n$$\n\n**Interpretation of Logistic Regression Performance (Test Set)**\n\n- Accuracy = 94.25%\nThe model correctly classified most cases, mainly because the dataset is highly imbalanced (only ~6% stroke cases). High accuracy here does not mean good stroke detection.\n\n- Sensitivity (True Positive Rate) = 0.017\nThe model correctly identified only 1 out of 59 actual stroke cases (≈1.7%).\n→ This shows the model fails to detect stroke cases, which is common in rare-event medical datasets.\n\n- Specificity (True Negative Rate) = 1.00\nThe model correctly classified all non-stroke cases.\n→ It is extremely good at predicting “No stroke,” which dominates the dataset.\n\n- Positive Predictive Value (Precision) = 1.00\nWhen the model predicts “Yes,” it is always correct — but it predicted “Yes” only once.\nHigh precision is misleading because the model rarely predicts a positive case.\n\n- Negative Predictive Value = 0.942\nMost “No” predictions are correct, matching the overall class imbalance.\n\n- Kappa = 0.031\nKappa measures agreement beyond chance. A value near zero shows the model performs only slightly better than random when considering class imbalance.\n\n- Balanced Accuracy = 0.508\nWhen weighting sensitivity and specificity equally, the model performs at chance level (~50%).\n→ Confirms that stroke detection is weak.\n\n- McNemar’s Test p < 0.0001\nStrong evidence that the model’s errors are systematically skewed—it overwhelmingly predicts “No stroke.”\n\nThe logistic regression model achieves high accuracy only because the negative class dominates.It detects almost no true stroke cases, giving extremely poor sensitivity.\nIt performs well for the majority class (non-stroke), but fails for the minority class (stroke).\n\nThese results highlight the challenge of severe class imbalance, which requires additional techniques (e.g., SMOTE, class weights, resampling) to improve medical-event prediction.\n\n**ROC curve and AUC for the logistic model**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sanity check\ntable(stroke_test$stroke)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n No Yes \n949  59 \n```\n\n\n:::\n\n```{.r .cell-code}\n# ROC and AUC using factor outcome directly\nroc_glm <- roc(\n  response  = stroke_test$stroke,    # factor: No / Yes\n  predictor = stroke_test$pred_prob, # predicted probabilities from glm\n  levels    = c(\"No\", \"Yes\"),        # \"No\" = control, \"Yes\" = case\n  direction = \"<\"\n)\n\nauc(roc_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.8154\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(roc_glm, main = \"ROC Curve – Logistic Regression (Test Set)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\nA higher AUC (closer to 1) indicates better discrimination between stroke and non-stroke cases. Values substantially above 0.5 indicate that the model performs better than random classification.\n\n**Interpretation of ROC Curve and AUC (Test Set)**\n\nThe ROC curve evaluates the model’s ability to distinguish between stroke and non-stroke cases across all possible classification thresholds, not just the default 0.5 cutoff.\n\nThe AUC = 0.815, which indicates good discriminative performance.\n\nAUC = 0.5 is  no discrimination (random guessing)\n\nAUC = 0.7–0.8 is acceptable\n\nAUC = 0.8–0.9 is good\n\nAUC > 0.9 is excellent\n\n- Even though the confusion matrix showed poor sensitivity at threshold 0.5, the AUC reveals that the model can separate the two classes reasonably well if a better threshold is chosen.\n\n- The strong AUC compared to weak sensitivity highlights the impact of severe class imbalance and the importance of customizing the probability cutoff for medical prediction tasks.\n\nOverall, the ROC analysis suggests that the logistic model contains useful predictive signal, but performance for detecting stroke can be improved with:\n\n- threshold tuning,\n\n- cost-sensitive training,\n\n- resampling techniques (SMOTE / oversampling).\n\n\n**Machine-learning model comparison**\n\n**Data Splitting and prepration**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_df <- strokeclean\nmodel_df <- na.omit(model_df)\nmodel_df$stroke <- factor(model_df$stroke)\nlevels(model_df$stroke) <- c(\"No\", \"Yes\")\ntable(model_df$stroke)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  No  Yes \n3177  180 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(123)\nindex <- createDataPartition(model_df$stroke, p = 0.70, list = FALSE)\ntrain_data <- model_df[index, ]\ntest_data  <- model_df[-index, ]\n\ntrain_data$stroke <- factor(train_data$stroke, levels = c(\"No\",\"Yes\"))\ntest_data$stroke  <- factor(test_data$stroke,  levels = c(\"No\",\"Yes\"))\n```\n:::\n\n\n**Train control settings**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctrl <- trainControl(\nmethod = \"repeatedcv\",\nnumber = 5,\nrepeats = 3,\nclassProbs = TRUE,\nsummaryFunction = twoClassSummary,\nverboseIter = FALSE\n)\n```\n:::\n\n\n\n**Logistic Regression (caret)**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_lr <- train(\nstroke ~ .,\ndata = train_data,\nmethod = \"glm\",\nfamily = \"binomial\",\nmetric = \"ROC\",\ntrControl = ctrl\n)\n```\n:::\n\n\n**Decision Tree**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_tree <- train(\nstroke ~ .,\ndata = train_data,\nmethod = \"rpart\",\nmetric = \"ROC\",\ntrControl = ctrl,\ntuneLength = 10\n)\n```\n:::\n\n\n**Random Forest**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_rf <- train(\nstroke ~ .,\ndata = train_data,\nmethod = \"rf\",\nmetric = \"ROC\",\ntrControl = ctrl,\ntuneLength = 5\n)\n```\n:::\n\n\n**Gradient Boosted Machine (GBM)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_gbm <- train(\nstroke ~ .,\ndata = train_data,\nmethod = \"gbm\",\nmetric = \"ROC\",\ntrControl = ctrl,\nverbose = FALSE\n)\n```\n:::\n\n\n**k-Nearest Neighbours (k-NN)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_knn <- train(\nstroke ~ .,\ndata = train_data,\nmethod = \"knn\",\nmetric = \"ROC\",\ntrControl = ctrl\n)\n```\n:::\n\n\n**Support Vector Machine (Radial)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_svm <- train(\nstroke ~ .,\ndata = train_data,\nmethod = \"svmRadial\",\nmetric = \"ROC\",\ntrControl = ctrl\n)\n```\n:::\n\n\n**Model evaluation on the test set**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels_list <- list(\nLR   = model_lr,\nTREE = model_tree,\nRF   = model_rf,\nGBM  = model_gbm,\nKNN  = model_knn,\nSVM  = model_svm\n)\n\nresults <- data.frame(\nModel       = character(),\nAUC         = numeric(),\nAccuracy    = numeric(),\nSensitivity = numeric(),\nSpecificity = numeric()\n)\n\nfor (m in names(models_list)) {\nmdl <- models_list[[m]]\n\n# Probabilities for the \"Yes\" class\n\npreds_prob  <- predict(mdl, test_data, type = \"prob\")[, \"Yes\"]\n\n# Class predictions\n\npreds_class <- predict(mdl, test_data)\n\n# ROC & AUC\n\nroc_obj <- roc(test_data$stroke, preds_prob,\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\nauc_val <- auc(roc_obj)\n\n# Confusion matrix – positive = \"Yes\"\n\ncm_m <- confusionMatrix(preds_class, test_data$stroke, positive = \"Yes\")\n\nresults <- rbind(\nresults,\ndata.frame(\nModel       = m,\nAUC         = as.numeric(auc_val),\nAccuracy    = cm_m$overall[\"Accuracy\"],\nSensitivity = cm_m$byClass[\"Sensitivity\"],\nSpecificity = cm_m$byClass[\"Specificity\"]\n)\n)\n}\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Model       AUC  Accuracy Sensitivity Specificity\nAccuracy     LR 0.7788854 0.9433962  0.00000000   0.9968520\nAccuracy1  TREE 0.6475263 0.9414101  0.01851852   0.9937041\nAccuracy2    RF 0.7275465 0.9433962  0.01851852   0.9958027\nAccuracy3   GBM 0.7636994 0.9453823  0.01851852   0.9979014\nAccuracy4   KNN 0.6633730 0.9463754  0.00000000   1.0000000\nAccuracy5   SVM 0.6256655 0.9453823  0.00000000   0.9989507\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\nAcross all six models, overall accuracy and specificity are very high, mainly because the dataset is highly imbalanced (only ~6% stroke cases). However, sensitivity is extremely low across every model, meaning that almost none of the models correctly identify stroke cases.\n\nLogistic Regression (AUC = 0.78) and GBM (AUC = 0.76) show the best overall discrimination, indicated by the highest AUC values. These models are better at ranking high-risk vs. low-risk individuals, even though they still fail at detecting positives under the default 0.5 threshold.\n\nTree-based models (Decision Tree, Random Forest, GBM) achieve slightly higher sensitivity than LR, but only marginally (still around 1–2%). KNN and SVM detect 0 stroke cases at this threshold, despite high accuracy.\n\nAll models appear to perform well based on accuracy and specificity, but this is misleading—they are failing at the most important task: detecting stroke cases. This confirms that class imbalance severely affects performance and requires threshold tuning, resampling, or cost-sensitive learning to achieve meaningful sensitivity.\n\n\n**ROC curve comparison across models**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ROC objects for each model\n\nroc_lr   <- roc(test_data$stroke,\npredict(model_lr,   test_data, type = \"prob\")[, \"Yes\"],\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\n\nroc_tree <- roc(test_data$stroke,\npredict(model_tree, test_data, type = \"prob\")[, \"Yes\"],\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\n\nroc_rf   <- roc(test_data$stroke,\npredict(model_rf,   test_data, type = \"prob\")[, \"Yes\"],\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\n\nroc_gbm  <- roc(test_data$stroke,\npredict(model_gbm,  test_data, type = \"prob\")[, \"Yes\"],\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\n\nroc_knn  <- roc(test_data$stroke,\npredict(model_knn,  test_data, type = \"prob\")[, \"Yes\"],\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\n\nroc_svm  <- roc(test_data$stroke,\npredict(model_svm,  test_data, type = \"prob\")[, \"Yes\"],\nlevels = c(\"No\", \"Yes\"), direction = \"<\")\n\n# Plot ROC curves\n\nplot(roc_lr,   col = \"red\",       main = \"ROC Comparison for Six Models\")\nplot(roc_tree, col = \"blue\",      add = TRUE)\nplot(roc_rf,   col = \"darkgreen\", add = TRUE)\nplot(roc_gbm,  col = \"purple\",    add = TRUE)\nplot(roc_knn,  col = \"orange\",    add = TRUE)\nplot(roc_svm,  col = \"black\",     add = TRUE)\n\nlegend(\n\"bottomright\",\nlegend = c(\"LR\", \"Tree\", \"RF\", \"GBM\", \"KNN\", \"SVM\"),\ncol    = c(\"red\", \"blue\", \"darkgreen\", \"purple\", \"orange\", \"black\"),\nlwd    = 2\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThe ROC curves show how well each of the six models distinguishes between stroke and non-stroke cases at all probability thresholds.  All models outperform random guessing (the diagonal line), indicating that they include useful predictive information.\n\n- Logistic Regression (red) and Gradient Boosted Machine (purple) have the most robust ROC curves, consistently outperforming the others across the majority of the sensitivity-specificity range. This is consistent with their higher AUC values, implying that these models provide the most accurate ranking of individuals by stroke risk. Random Forest (green) also performs well, trailing just LR and GBM, demonstrating its capacity to capture nonlinear interactions.\n\n- The Decision Tree, k-NN, and SVM models have weaker curves, indicating lower discriminative capacity than the ensemble-based and logistic models.  SVM (black) performs the worst, remaining closest to the diagonal, implying little distinction between classes.\n\nOverall, the ROC comparison reveals that, while all models outperform chance, Logistic Regression, GBM, and Random Forest provide the best trade-off between sensitivity and specificity, despite the fact that sensitivity remains low at the default threshold due to severe class imbalance.\n \n\n**Odds ratios and risk stratification**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_lr <- glm(\nstroke ~ age + gender + hypertension + heart_disease + ever_married +\nwork_type + Residence_type + avg_glucose_level + bmi + smoking_status,\ndata   = train_data,\nfamily = binomial\n)\n\nlr_coef <- summary(glm_lr)$coefficients\n\n# Odds ratios and 95% CI\n\nor_vals <- exp(lr_coef[, \"Estimate\"])\nci_raw  <- suppressMessages(confint(glm_lr)) # CI on log-odds scale\nci_or   <- exp(ci_raw)                       # convert to OR scale\n\nplot_df <- data.frame(\nPredictor = rownames(lr_coef),\nOR        = or_vals,\nCI_lower  = ci_or[, 1],\nCI_upper  = ci_or[, 2]\n)\n\nplot_df <- subset(plot_df, Predictor != \"(Intercept)\")\n\nggplot(plot_df, aes(x = reorder(Predictor, OR), y = OR)) +\ngeom_point(size = 3, color = \"red\") +\ngeom_errorbar(aes(ymin = CI_lower, ymax = CI_upper), width = 0.2) +\ncoord_flip() +\nlabs(\ntitle = \"Odds Ratios for Stroke Predictors (Logistic Regression)\",\ny     = \"Odds Ratio (log scale)\",\nx     = \"\"\n) +\nscale_y_log10() +\ngeom_hline(yintercept = 1, linetype = \"dashed\") +\ntheme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot_df[order(-plot_df$OR), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  Predictor        OR  CI_lower CI_upper\nhypertension                   hypertension 2.5159353 1.6453888 3.810548\never_married                   ever_married 1.7023436 0.9357451 2.967095\nheart_disease                 heart_disease 1.4392416 0.8218664 2.439382\nsmoking_statusSmokes   smoking_statusSmokes 1.4246818 0.8360264 2.380571\nsmoking_statusFsmoked smoking_statusFsmoked 1.2340439 0.7883483 1.920422\ngenderFemale                   genderFemale 1.1132391 0.7481511 1.670149\nage                                     age 1.0804344 1.0630608 1.099392\navg_glucose_level         avg_glucose_level 1.0054691 1.0021701 1.008745\nbmi                                     bmi 1.0025648 0.9719311 1.032772\nResidence_typeRural     Residence_typeRural 0.9325388 0.6311308 1.374361\nwork_type                         work_type 0.8371811 0.6210602 1.130333\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\nThe odds-ratio graphic illustrates how each predictor affects the risk of having a stroke while keeping all other variables constant.  Values greater than 1 imply higher odds, whereas values less than 1 indicate lower odds.  Confidence intervals that do not cross 1 indicate statistically significant evidence.\n\n- Hypertension (OR ≈ 2.52, CI: 1.65–3.81)\nHypertension is one of the strongest predictors of stroke. Individuals with hypertension have more than 2.5 times higher odds of stroke compared to non-hypertensive individuals. The confidence interval does not cross 1, indicating strong statistical significance.\n\n- Age (OR ≈ 1.08 per year, CI: 1.06–1.10)\nEach additional year of age increases stroke odds by about 8%, making age a consistent and significant risk factor.\n\n- Average glucose level (OR ≈ 1.005, CI: 1.002–1.009)\nHigher glucose levels slightly increase stroke odds. Although the effect size is small, the very tight CI above 1 suggests a reliable association linked to metabolic risk.\n\n- Heart disease (OR ≈ 1.44, CI: 0.82–2.44)\nPeople with heart disease show elevated stroke odds (≈44% higher), but the CI crosses 1, meaning evidence is suggestive but not statistically conclusive in this dataset.\n\n- Smoking behavior:\n\n- Current smokers (OR ≈ 1.42)\n\n- Former smokers (OR ≈ 1.23)\nBoth groups show increased stroke odds compared to never-smokers, though their confidence intervals cross 1. This indicates a positive trend consistent with clinical knowledge, but weaker statistical support here.\n\n- Ever married (OR ≈ 1.70, CI: 0.94–2.97)\nShows higher odds of stroke, but the wide CI overlapping 1 indicates uncertainty.\n\n- Gender (Female) (OR ≈ 1.11, CI: 0.75–1.67)\nMinimal effect, not statistically significant.\n\n- BMI (OR ≈ 1.00)\nVirtually no effect on stroke odds.\n\n- Residence type (Rural vs Urban) (OR ≈ 0.93)\nNo meaningful association with stroke.\n\n- Work type (OR ≈ 0.84)\nSlightly lower odds of stroke, but not statistically meaningful.\n\n**Threshold tuning to 0.2 from 0.5**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Threshold tuning: use 0.2 instead of 0.5\nnew_threshold <- 0.2\n\nstroke_test$pred_class_02 <- ifelse(stroke_test$pred_prob >= new_threshold,\n                                    \"Yes\", \"No\")\n\nstroke_test$pred_class_02 <- factor(stroke_test$pred_class_02,\n                                    levels = c(\"No\", \"Yes\"))\n\n# Confusion matrix for threshold = 0.2\ncm_02 <- confusionMatrix(\n  data      = stroke_test$pred_class_02,\n  reference = stroke_test$stroke,\n  positive  = \"Yes\"\n)\n\ncm_02\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction  No Yes\n       No  903  46\n       Yes  46  13\n                                          \n               Accuracy : 0.9087          \n                 95% CI : (0.8892, 0.9258)\n    No Information Rate : 0.9415          \n    P-Value [Acc > NIR] : 1               \n                                          \n                  Kappa : 0.1719          \n                                          \n Mcnemar's Test P-Value : 1               \n                                          \n            Sensitivity : 0.22034         \n            Specificity : 0.95153         \n         Pos Pred Value : 0.22034         \n         Neg Pred Value : 0.95153         \n             Prevalence : 0.05853         \n         Detection Rate : 0.01290         \n   Detection Prevalence : 0.05853         \n      Balanced Accuracy : 0.58593         \n                                          \n       'Positive' Class : Yes             \n                                          \n```\n\n\n:::\n:::\n\n\n**Interpretation (threshold = 0.2)**\n\n- With a lower decision criterion of 0.2, the model successfully identifies 13 out of 59 stroke cases (sensitivity = 22%), compared to only one case with the default 0.5 threshold.\n\n- Specificity remains high at almost 95%, indicating that the majority of non-stroke patients are still properly categorized as \"no stroke\" (903 out of 949).\n\n- While overall accuracy declines from 94% to 91%, balanced accuracy improves (from ≈0.51 to ≈0.59), indicating a greater balance of sensitivity and specificity.\n\nThis change indicates a therapeutically reasonable compromise: the model detects more possible stroke patients (fewer missed cases) at the expense of a moderate rise in false positives.\n\n\n# conclusion\n\nThis experiment compared a conventional logistic regression model with several machine-learning algorithms and examined whether common demographic, behavioral, and clinical characteristics may be used to predict stroke risk using a stroke dataset. Stroke was a rare outcome (about 5% of cases) in the final sample of 3,357 people that was analyzed after the data was cleaned and inconsistent or missing values were eliminated. In addition to reflecting actual epidemiology, this significant class disparity complicates classification, particularly when it comes to identifying the minority (stroke) class.\n\nAge, hypertension, cardiac disease, and raised average glucose levels are among the best predictors of stroke, according to the baseline logistic regression model. Smoking status substantially increased risk.  These variables were identified as significant risk factors by odds ratios significantly greater than 1 and confidence intervals that did not cross 1.  These results support the use of logistic regression as an interpretable tool for comprehending the relationship between particular risk variables and the likelihood of stroke and are in line with the clinical literature on cerebrovascular illness.\n\nThe logistic regression model performed reasonably well overall in terms of prediction; however, sensitivity for stroke cases was more constrained at the default 0.5 probability threshold, as would be expected with an imbalanced outcome.  The model clearly outperformed random guessing, according to the ROC curve and AUC values, but there was still space for improvement in terms of differentiating between stroke and non-stroke patients.  Youden's J statistic offers a method for selecting a different categorization threshold that enhances the ratio of sensitivity to specificity, which may be crucial in a screening setting when it is expensive to miss actual stroke cases.\n\nMore sophisticated models, such Random Forest and Gradient Boosted Machine, were able to attain somewhat higher AUC values than logistic regression in the machine-learning comparison, showing superior discrimination across a range of thresholds.  However, these increases in AUC came at the expense of decreased interpretability and were not always accompanied by significant increases in sensitivity at fixed cut-offs.  Logistic regression, on the other hand, offers precise odds ratios and confidence intervals that are simpler for public health professionals and doctors to understand when discussing risk and developing interventions.\n\nBecause of the severe class imbalance, sensitivity for stroke cases was extremely low (around 2%), meaning that the model almost never predicted “stroke = Yes” and therefore missed most true stroke cases.\n\nTo address this, the decision threshold was lowered from 0.5 to 0.2. At this cut-off, sensitivity increased from roughly 2% to about 22%, while specificity remained high at around 95%. Overall accuracy dropped slightly to about 91%, but balanced accuracy improved, indicating a more reasonable trade-off between detecting stroke cases and avoiding false positives. This threshold experiment illustrates a key practical point: for rare but serious outcomes such as stroke, it can be preferable to sacrifice some overall accuracy in order to reduce the number of missed high-risk individuals. In this setting, the logistic model is more appropriately viewed as a screening or risk-flagging tool rather than a definitive diagnostic rule.\n\nOverall, the findings show that relatively simple models built from routinely collected health indicators can meaningfully distinguish between individuals with and without stroke, even in the presence of substantial class imbalance. Logistic regression emerges as a strong, interpretable baseline, while tree-based ensemble methods provide incremental performance improvements at the cost of transparency. Future work could focus on external validation, calibration assessment, more sophisticated imbalance-handling techniques, and the inclusion of additional clinical or longitudinal information. These extensions would help move from proof-of-concept modelling toward robust, clinically usable tools for stroke risk stratification and targeted prevention.\n\n\n#References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}