on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ~/.R/library
   
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev
      
      - name: Install base system dependencies for R packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
      
      - name: Create user R library
        run: mkdir -p $R_LIBS_USER
      
      - name: Install getsysreqs
        run: |
          Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org')"
          Rscript -e ".libPaths(c(Sys.getenv('R_LIBS_USER'), .libPaths())); remotes::install_github('mdneuzerling/getsysreqs')"
          Rscript -e ".libPaths(c(Sys.getenv('R_LIBS_USER'), .libPaths())); library(getsysreqs); packageVersion('getsysreqs')"

      - name: Install getsysreqs and dependencies
        run: |
          install.packages("remotes")
          remotes::install_github("mdneuzerling/getsysreqs")
        shell: Rscript {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system dependencies
        run: |
          Rscript -e ".libPaths(c(Sys.getenv('R_LIBS_USER'), .libPaths())); \
            sysreqs <- getsysreqs::get_sysreqs('website/renv.lock', distribution='ubuntu', release='22.04'); \
            cat(sysreqs)"
          sysreqs=$(Rscript -e ".libPaths(c(Sys.getenv('R_LIBS_USER'), .libPaths())); cat(getsysreqs::get_sysreqs('website/renv.lock', distribution='ubuntu', release='22.04'))")
          if [ ! -z "$sysreqs" ]; then
            echo "Installing system requirements: $sysreqs"
            sudo apt-get update -y
            sudo apt-get install -y --no-install-recommends $sysreqs
          else
            echo "No system requirements found."
          fi
        shell: bash

      # Need to setup to use RENV
      - name: Setup RENV
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: website
          # profile: '"shiny"'
     
      # - name: Set up Quarto
      #   uses: quarto-dev/quarto-actions/setup@v2

      # - name: install dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages:
      #       any::knitr
      #       any::rmarkdown
      #       any::downlit
      #       any::xml2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}