on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install libcurl dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
      
      - name: Install getsysreqs and dependencies
        run: |
          install.packages("remotes")
          remotes::install_github("mdneuzerling/getsysreqs")
        shell: Rscript {0}

      - name: Install system dependencies
        run: |
          cd website
          sysreqs=$(Rscript -e "cat(getsysreqs::get_sysreqs("renv.lock",distribution = "ubuntu", release = '22.04'))")
          if [ ! -z "$sysreqs" ]; then
            echo "Installing system requirements: $sysreqs"
            sudo apt-get update -y
            sudo apt-get install -y --no-install-recommends $sysreqs
          else
            echo "No system requirements found."
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Need to setup to use RENV
      - name: Setup RENV
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: website
          # profile: '"shiny"'
     
      # - name: install dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages:
      #       any::knitr
      #       any::rmarkdown
      #       any::downlit
      #       any::xml2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}