name: Render and Publish
on:
  push:
    branches:
      - main
    paths:
      - 'website/_site/*'

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v5
          
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.4.515

        # - name: Render Quarto Project
        #   uses: quarto-dev/quarto-actions/render@v2
        #   with:
        #     # to: html # If set, it will be equivalent to `quarto render --to html`
        #     path: website

        - name: Publish to GitHub Pages
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages # renderred html files will be pushed here
            path: website
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions